### ISSUE TITLE
Checkbox indeterminate state

### ISSUE THREAD

**Issue by Gbacc** [picturepan2/spectre#102]
Hi and first thanks for your work here.

While trying to use your lib i had to use indeterminate state checkbox.
If you mind adding it here is the css 

`.form-checkbox input:indeterminate + .form-icon::after {
    background-clip: padding-box;
    border: .2rem solid #fff;
    border-left-width: 0;
    border-top-width: 0;
    border-bottom-width: 0;
    content: "";
    height: 1rem;
    left: 50%;
    margin-left: -.3rem;
    margin-top: -.7rem;
    position: absolute;
    top: 50%;
    -ms-transform: rotate(90deg);
    transform: rotate(90deg);
    width: .6rem;
}`

**Comment by picturepan2** [comment]
I will add it. Thank you for the suggestion.

**Comment by picturepan2** [comment]
Updated https://github.com/picturepan2/spectre/pull/103
