### ISSUE TITLE
Text inputs in tab

### ISSUE THREAD

**Issue by tleb** [picturepan2/spectre#104]
Hey!

Is there a way to have a nicely formatted text input in a tab? [This](https://jsfiddle.net/k6mc5usa/1/) is what I have right now. Is there a class planned for this type of thing? Or should I increase the height of the tab manually?

Thanks for the lib!

Edit: Using `input-sm`, the input fits, but what can I do to center the input in the tab?

**Comment by picturepan2** [comment]
@tleb I will consider it. The difficult part is code it for responsive layout. I will try some solutions. Thank you.

**Comment by picturepan2** [comment]
@tleb Hi, I have added tabs with text input example in the docs here https://picturepan2.github.io/spectre/components.html#tabs .
