### ISSUE TITLE
Horizontal forms are broken 

### ISSUE THREAD

**Issue by b3njamin** [picturepan2/spectre#105]
https://github.com/picturepan2/spectre/commit/58e8e7e600c8fb0e2c292e8a74818a5a1b587c64#diff-980fbaf92d0de3252521be1693f2c51eR305

**Comment by picturepan2** [comment]
Yes. I have changed some responsive layout codes. If you cannot migrate your code. Please tell me.

**Comment by picturepan2** [comment]
@b3njamin I am closing this issue now because it is a migration problem. If you need any help, please let me know. Thank you.
