### ISSUE TITLE
Safari hidden pull-left

### ISSUE THREAD

**Issue by martinsookael** [picturepan2/spectre#107]
`
<input type="text" id="someInput" class="form-control pull-left hidden">
`

If i remove the class "hidden", then in Safari (testing with Version 9.1.1 (11601.6.17) then the element remains hidden (hovering the element in Elements the browser shows that it's placed somewhere in a screen with sizes: 0px 0px.

If I remove "pull-left", showing and removing hidden works as expected.

**Comment by picturepan2** [comment]
@martinsookael These are no `pull-left` and `hidden` classes in Spectre.css. What CSS frameworks/libs are you using?
