### ISSUE TITLE
Some pointers/Q's

### ISSUE THREAD

**Issue by tommiehansen** [picturepan2/spectre#109]
Spectre seems to be a great way to start something.
But while some things seems great, some things would benefit from being a tad better.
1. What is `variables.less` ? Consider adding this part to base.less; base should be "all things base", in this case many things that reside inside `variables.less` should be considered being 'base'.
2. Exclude "non-base" things from `variables.less` such as `.toast-variant(@color)` which is something that only toasts use and therefor should not be considered 'base'.
3. Colors are one of the first things any serious project would change. Therefor this needs to be simpler to change and should rather be key then something hidden away inside `variables.less`. 
   Consider moving `// Colors` to a new `colors.less`. Also consider including 3rd party color options (optional; as a resource) if the user wants it. Palettes such as https://rawgit.com/tommiehansen/tommie-material-colors/master/material.html could be used but could be hard since spectre bases it's colors on darken() and lighten() therefore the coloring part also needs to be rewritten to add and support darker/lighter variants on a base color without resorting to using `darken()` and `lighten()`

```
@import 'material-colors.less';

// Primary
@color: @blue-500;
@color-primary: @color;  // register verbose variant for later verbosity if needed
@color-primary-1: @color; // ---"---
@color-primary-2: @blue-800;
@color-primary-3: @blue-700;
@color-primary-4: @blue-600;
@color-primary-5: @blue-400;
@color-primary-6: @blue-200;
@color-primary-7: @blue-50;

// Secondary
@secondary: @amber-500;
@color-secondary: @secondary;  // register verbose variant for later verbosity if needed
@color-secondary-1: @color; // ---"---
@color-secondary-2: @amber-800;
@color-secondary-3: @amber-700;

....etc...

```

Example: http://codepen.io/tommiehansen/pen/EgLmPB?editors=0100

**Comment by picturepan2** [comment]
@tommiehansen Hi, thank you for the questions. Let me explain the ideas behind it. 
The variables.less is a centralized place for all variables that have been used in Spectre.css. It includes colors, sizes, layouts and mixins, not limited to base.less.

I will consider that color options. Also, I will make it more clear on both code and doc sides. Thank you.

**Comment by tommiehansen** [comment]
@picturepan2 Thanks for the response,  
I understand why you would do it that way but again; the colors is one of the first thing someone would alter so it really needs to stand out and one really needs to be able to design brightness schemes and such things. Using darken() lighthen() is good for grays but mostly sucks for laying out colors throughout a document, ie:

```
@color-base: #4cf;
...
...
...
LOT'S OF CODE
...
...
...
.myText { color: darken(@color-base, 10%); }
```

The example above would make it hard to control what sort of `darken` is applied.  
This is preferrable:

```
@color-base: #4cf;
@color-base-dark: darken(@color-base, 10%);
...
...
...
LOT'S OF CODE
...
...
...
.myText {  color: @color-base-dark; }
```

**Comment by picturepan2** [comment]
@tommiehansen Color variables have been totally improved as you suggest in https://github.com/picturepan2/spectre/releases/tag/v0.2.5. Thank you.

**Comment by tommiehansen** [comment]
@picturepan2 Great 👍
