### ISSUE TITLE
Adding col-multiline to the documentation or make it the standard behaviour of columns

### ISSUE THREAD

**Issue by tobiassernhede** [picturepan2/spectre#111]
Great framework, really dig it so far.

Only problem I had was that the columns didn't wrap appropriately when on different sizes. Found out by searching here on github that you have fixed this by adding the .col-multiline class.

But this is not explained in the documentation and thus hard to find.

https://github.com/picturepan2/spectre/pull/86
https://github.com/picturepan2/spectre/issues/64

I would also argue for this being the standard behaviour of how columns work when wrapping instead of being invisible (outside of the window), without the need to add an extra class.
If I want to intentionally hide something on different screen sizes you have great helpers with hide-xs etc. Also .col-oneline

**Comment by guillaumemolter** [comment]
Agreed this is a very strange behavior.

**Comment by picturepan2** [comment]
@tobiassernhede The `col-multiline` is now the default behavior of the flexbox based columns. You can use `.col-oneline` for a single line column.
