### ISSUE TITLE
Content aligned left in tables

### ISSUE THREAD

**Issue by karmasakshi** [picturepan2/spectre#113]
Hi,

I was wondering if removing `text-align: left` from `.table th` and `.table td` would be a good idea. They override alignment classes (like `.text-center`) when applied to `td` due to specificity.

**Comment by picturepan2** [comment]
@karmasakshi It has been fixed in https://github.com/picturepan2/spectre/pull/127/commits/cf7d1a4ae8f46d09006340303ca13c2fe3a03d40. The alignment classes now works with table.
