### ISSUE TITLE
Widescreen responsiveness

### ISSUE THREAD

**Issue by alexandremjacques** [picturepan2/spectre#115]
Any reason why there's no support for screen (widths) greater than 960px in responsive grids? Nowadays wider screens with greater resolutions are a common place.

I ask because my app must support IE 10+ and flexbox is still too buggy on IE.

I know that I can customize Spectre (which I do), but it would be nice no have this by default since it would not be opnionated (just more breakpoints above 960px).

Thanks for the great work!! Really like the design.

**Comment by picturepan2** [comment]
@alexandremjacques Thanks, I am adding more layout widths.

**Comment by victorparmar** [comment]
I needed this as well and just raised https://github.com/picturepan2/spectre/pull/183 to add 1200 grid support :)
