### ISSUE TITLE
Spectre JS Components

### ISSUE THREAD

**Issue by roemhildtg** [picturepan2/spectre#117]
This isn't so much a issue as a fyi, I've been throwing together a few components in spectre that would require js and I figured I'd leave a little request to see if I could get some feedback on the project. 

Suggestions would be appreciated :)

[The repo is here](https://github.com/roemhildtg/spectre-canjs)

**Comment by forbesmyester** [comment]
The lack of JS libs etc in Spectre was one of the key reasons for selecting Spectre for me. So many require JQuery or something... We're hosting many different projects currently in Both Angular 1 and Angular 2 and want a consistent look... I'm not particularly a fan of debugging why JQuery A with Spectre B doesn't interact well with Angular C on Browser D. For that matter if I were doing React I'd not be a fan of DOM mutations occurring outside of my control.

**Comment by roemhildtg** [comment]
Me also. I regularly work with other libs besides jquery, and didn't want to use bootstrap for that reason. Made the call to switch to spectre and haven't regretted that decision since.

**Comment by tommiehansen** [comment]
@forbesmyester  I agree that it isn't great if a library requires some is library. However a few examples written pure is or library A or B hardly hurts anyone. This even though we that build entire systems tend to roll our own, optimized, code anyway.

**Comment by roemhildtg** [comment]
Just found another project of js spectre components: https://github.com/vace/vue-spectre
