### ISSUE TITLE
Bring back Navbar

### ISSUE THREAD

**Issue by ThunderRoid** [picturepan2/spectre#118]
Hi @picturepan2, it has been almost 5 months, please bring back the Navbar.
Thanks
BTW, **spectre** rocks
Awesome job man

**Comment by roemhildtg** [comment]
I second this proposal. A responsive navbar would be a fantastic addition to the project.

**Comment by posemon** [comment]
I third this proposal. It would be great.

**Comment by ThunderRoid** [comment]
@picturepan2 any comment ???

**Comment by picturepan2** [comment]
@ThunderRoid Bringing back.

**Comment by kirqe** [comment]
Nav with dropdown menus plz

**Comment by roemhildtg** [comment]
@kirqe There's an issue I created about this, but it doesn't work on ios. any ideas on how to make this work with ios? https://github.com/picturepan2/spectre/issues/126

**Comment by kazuemon** [comment]
Why was navbar deleted?

**Comment by kazuemon** [comment]
nice update :3

**Comment by kazuemon** [comment]
navbar-brand not found??

**Comment by picturepan2** [comment]
@kazuemon `navbar-brand` is an opinionated style which I leave it in the index.html head.

**Comment by picturepan2** [comment]
Navbar is back and simplified. https://github.com/picturepan2/spectre/pull/127

**Comment by ThunderRoid** [comment]
@picturepan2 NavBar is not Mobile (small) device friendly.
![image](https://cloud.githubusercontent.com/assets/3328263/21739504/634a9c84-d451-11e6-98c6-257b6930edc8.png)

**Comment by picturepan2** [comment]
@ThunderRoid Yes, that was the reason I removed the Navbar out of the Spectre. Still thinking how to improve it.

**Comment by roemhildtg** [comment]
@picturepan2 [here's a cool horizontal to vertical nav example](http://purecss.io/layouts/tucked-menu/). The switching does require a small piece of javascript but spectre could implement the css side of it.
