### ISSUE TITLE
is-danger, has-danger does not work fully with "select"

### ISSUE THREAD

**Issue by ThunderRoid** [picturepan2/spectre#121]
![error](https://cloud.githubusercontent.com/assets/3328263/20256931/55f0c9d0-a9fb-11e6-859b-694f867ee3a4.png)

Select box doesnot turn red, only text turns red
"form-input-hint" with Radio is broken (should be below instead of beside)

**Comment by picturepan2** [comment]
@ThunderRoid Thanks. I will fix it.

**Comment by picturepan2** [comment]
Btw, you could use `form-group` for different set of form elements. In that way, the raido options will be below the `select` element.

**Comment by picturepan2** [comment]
@ThunderRoid Now `form-select` elements can have success or danger style. Same usage as the `form-input` elements. https://github.com/picturepan2/spectre/pull/124

**Comment by ThunderRoid** [comment]
@picturepan2 Thanks  so much
