### ISSUE TITLE
HTML hidden Attribute does not work with "form-input-hint"

### ISSUE THREAD

**Issue by ThunderRoid** [picturepan2/spectre#122]
HTML hidden Attribute - http://www.w3schools.com/TAgs/att_global_hidden.asp
does not work with "form-input-hint", because it conflicts with "display: inline-block;" property of "form-input-hint" class, many library depends on this Attribute for error message handling - like AngularJS
```html
<span hidden class="form-input-hint">The name is invaild.</span>
```

**Comment by picturepan2** [comment]
I have updated Spectre to version 0.1.29 and the issue should have been fixed. Thanks.

**Comment by ThunderRoid** [comment]
@picturepan2 Awesome, thanks again.
