### ISSUE TITLE
Suggestion: Add danger and success styles to buttons and labels

### ISSUE THREAD

**Issue by roemhildtg** [picturepan2/spectre#128]
![image](https://cloud.githubusercontent.com/assets/5471079/21573120/7c07b94c-cea6-11e6-8641-5ecb132cb953.png)

What do you think about adding the toast and form style colors to additional items like buttons and labels? I could make a pull request if you think it would benefit the project.

**Comment by picturepan2** [comment]
@roemhildtg  I am adding success and danger colors for labels. I will see if people need these colors for buttons. Also, a new color for buttons means bigger size.
