### ISSUE TITLE
Setup build process

### ISSUE THREAD

**Issue by marcobiedermann** [picturepan2/spectre#13]
Currently there is are no instructions how to transpile Less to CSS.
I suggest using a build task runner like NPM, Gulp or Grunt.

If done so, it might be helpful, to add some information to `readme.md`

**Comment by picturepan2** [comment]
I did use WebStorm built-in tool to compile files. I have a branch local for using Gulp. Doing more tests to make sure everything works fine. Yes, I will add those to Readme.

**Comment by picturepan2** [comment]
Done. I merged the Gulp support branch into `master`. You can have a test by using `gulp build`. Thanks.

**Comment by marcobiedermann** [comment]
@picturepan2 👍  Nice, will check it out later on :)

**Comment by marcobiedermann** [comment]
Fixed in 0c1b1641e07cab0d511ba73e96fb89f7cb042a81
