### ISSUE TITLE
btn-group with tooltip

### ISSUE THREAD

**Issue by performatric** [picturepan2/spectre#132]
Hello,
The ```btn-group``` with tooltip on the buttons is generating scrollbars.

![btn-group](https://cloud.githubusercontent.com/assets/11164643/21647119/291d6154-d280-11e6-97a2-25886012117f.png)

**Comment by picturepan2** [comment]
@performatric I am checking this issue.

**Comment by picturepan2** [comment]
@performatric It has been fixed https://github.com/picturepan2/spectre/pull/136.
