### ISSUE TITLE
Twitter Bootstrap ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [picturepan2/spectre#134]
# responsive CSS framework ? Bootstrap : spectre

![xxx](https://cloud.githubusercontent.com/assets/18028768/22184190/bb507526-e107-11e6-9da8-598bfcbeb671.PNG)

**Comment by picturepan2** [comment]
@xgqfrms-GitHub Read this line first https://github.com/AliasIO/Wappalyzer/blob/b0bc61bca74a857275087905b22575d0fefdef78/src/apps.json#L7427
