### ISSUE TITLE
Make hide classes more specific

### ISSUE THREAD

**Issue by MkaaaaaaaY** [picturepan2/spectre#143]
Make hide classes more specific or is there a reason why you dont do that ?

// Down
@media screen and (max-width: @size-xs) {
  .hide-xs-down {
    display: none !important;
  }
}

@media screen and (max-width: @size-sm) {
  .hide-sm-down {
    display: none !important;
  }
}

@media screen and (max-width: @size-md) {
  .hide-md-down {
    display: none !important;
  }
}

@media screen and (max-width: @size-lg) {
  .hide-lg-down {
    display: none !important;
  }
}

@media screen and (max-width: @size-xl) {
  .hide-xl-down {
    display: none !important;
  }
}

// Up
@media screen and (min-width: @size-xs) {
  .hide-xs-up {
    display: none !important;
  }
}

@media screen and (min-width: @size-sm) {
  .hide-sm-up {
    display: none !important;
  }
}

@media screen and (min-width: @size-md) {
  .hide-md-up {
    display: none !important;
  }
}

@media screen and (min-width: @size-lg) {
  .hide-lg-up {
    display: none !important;
  }
}

@media screen and (min-width: @size-xl) {
  .hide-xl-up {
    display: none !important;
  }
}

// Only
@media screen and (max-width: @size-xs) {
  .hide-xs {
    display: none !important;
  }
}

@media screen and (min-width: @size-sm) and (max-width: @size-md) {
  .hide-sm {
    display: none !important;
  }
}

@media screen and (min-width: @size-md) and (max-width: @size-lg ) {
  .hide-md {
    display: none !important;
  }
}

@media screen and (min-width: @size-lg) and (max-width: @size-xl) {
  .hide-lg {
    display: none !important;
  }
}

@media screen and (min-width: @size-xl) {
  .hide-xl {
    display: none !important;
  }
}

**Comment by picturepan2** [comment]
@MkaaaaaaaY Good suggestion. Thank you.
