### ISSUE TITLE
tooltips z-index

### ISSUE THREAD

**Issue by Antatip** [picturepan2/spectre#148]
Hi,

I noticed that when I set a tooltip-right for a "step" component, the tooltip is behind step dots.
Is it normal ?
Here Is my code.
`<ul class="step">`
`      <li class="step-item">`
`        <a class="tooltip tooltip-right" data-tooltip="Step 1">Step 1</a>`
`      </li>`
`      <li class="step-item">`
`        <a href="#" class="tooltip" data-tooltip="Step 2">Step 2</a>`
`      </li>`
`      <li class="step-item">`
`        <a href="#" class="tooltip" data-tooltip="Step 3">Step 3</a>`
`      </li>`
`      <li class="step-item">`
`        <a href="#" class="tooltip tooltip-left" data-tooltip="Step 4">Step 4</a>`
`      </li>`
`    </ul>`

**Comment by picturepan2** [comment]
@Antatip I am looking into this bug. Thank you.

**Comment by picturepan2** [comment]
Confirmed. I will fix it soon in next version.
You can fix it by changing the .tooltip `z-index` to any number higher than 99.

**Comment by Antatip** [comment]
Thank you ;) already done.

**Comment by picturepan2** [comment]
Fixed in https://github.com/picturepan2/spectre/pull/149. Thank you.
