### ISSUE TITLE
Show all icons?

### ISSUE THREAD

**Issue by neosin** [picturepan2/spectre#150]
I see passing mention to the ability to use icons (in buttons, etc) but I do not see any list of the available icons for use. Can you please include one so that people know which icons are available in a visual manner?

thanks

**Comment by picturepan2** [comment]
Spectre.css uses Google's Material Design icons for demo, and it is a font icon set. You can find all these icons in /docs/font/demo.html.

**Comment by roemhildtg** [comment]
Found them 😄 
https://picturepan2.github.io/spectre/font/demo.html

**Comment by picturepan2** [comment]
@roemhildtg Yep! You are right. I primarily use Icomoon for font icon.

**Comment by tobi-or-not-tobi** [comment]
The link seems to be broken. I'd like to use some google material icons as well, is there an updated link or have things changed?

**Comment by roemhildtg** [comment]
I don't know if there's still a demo, but you can at least get the list of icons here: https://github.com/picturepan2/spectre/blob/0.2.15/src/icons.less

**Comment by tobi-or-not-tobi** [comment]
Thanks, I've seen those and they're cool and documentation if fine. I just need a few other icons (i.e. video pause/play), so I'd either need to include a third party icon or build my own. I'm typically using the material icons in projects and to that reason i was interested to see how to best include those.

**Comment by roemhildtg** [comment]
I've used font awesome. Works pretty well.
