### ISSUE TITLE
Dropdown not workin in ios safari. 

### ISSUE THREAD

**Issue by inseldesign** [picturepan2/spectre#154]
Hey,

First of all: thanks for this outstanding framework and invested time. I realized that dropdowns are not working on ios safari (newest version).

Cheers

Sascha

**Comment by roemhildtg** [comment]
Did you add `tabindex="1"` to your link?

```html
<a href="#" onclick="javascript:return false;" tabindex="1" class="btn btn-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Apps
  <i class="caret fa fa-caret-down"></i>
</a>
```

**Comment by picturepan2** [comment]
@inseldesign `tabindex` is needed when you activate dropdown menus with focus state. Or you can write your own JS code.

**Comment by inseldesign** [comment]
Ok just tried your documentation page on a desktop computer and on tablet. #ux

**Comment by picturepan2** [comment]
@inseldesign Yes, thanks. I will improve this part.
