### ISSUE TITLE
grid-480 container missing?

### ISSUE THREAD

**Issue by mp4096** [picturepan2/spectre#156]
It seems like you've [deleted the `grid-480` container type](https://github.com/picturepan2/spectre/commit/5444d9416dd655d5dbab1567b60e4facc3766ca1#diff-7eb8a5752175cb6f44342b62083fb1c8L1218) in 5444d9416dd655d5dbab1567b60e4facc3766ca1. 

Was it really intended? We're actively using it and really miss it in the newer versions.

And thank you for the great library! :smiley: :cake:

**Comment by picturepan2** [comment]
@mp4096 My fault. I will fix it.

**Comment by picturepan2** [comment]
@mp4096 Grid-480 is back in v0.2.7 (https://github.com/picturepan2/spectre/pull/157). Please update it.

**Comment by mp4096** [comment]
Yep, it worked. Thank you!
