### ISSUE TITLE
menu inside autocomplete should have absolute position

### ISSUE THREAD

**Issue by borisirota** [picturepan2/spectre#158]
Hi,

In [v.0.1.26](https://github.com/picturepan2/spectre/blob/v0.1.26/src/autocomplete.less#L45) the `position` of the `form-autocomplete-list` was `absolute`. In later versions it was refactored to use `menu` instead of `form-autocomplete-list`.

`menu` inside `dropdown` [here](https://github.com/picturepan2/spectre/blob/master/src/dropdowns.less#L10) does have correct position.

Thanks !

**Comment by picturepan2** [comment]
@borisirota Hi, I have improved this part in https://github.com/picturepan2/spectre/releases/tag/v0.2.8.

**Comment by borisirota** [comment]
@picturepan2 thanks!
