### ISSUE TITLE
Tab view using pure CSS

### ISSUE THREAD

**Issue by Leva7** [picturepan2/spectre#161]
There are tab elements and we can select a tab by giving it the `active` class. But this means that we're not able to display currently active tabs using CSS only.  
A workaround could be to copy the active tab's rules and use a radiobutton tab solution but is there perhaps a better way?

**Comment by picturepan2** [comment]
@Leva7 The experimental [pure CSS Carousels](https://picturepan2.github.io/spectre/experimentals.html#carousels) are achieved by the radios. I will see if it is needed to add.

**Comment by alexbagirov** [comment]
Hi! He means switching content of *Tabs* component.
![screenshot_20170314-131339](https://cloud.githubusercontent.com/assets/6885864/23891446/3c5b5816-08b8-11e7-9d33-40e66e131b70.png)

**Comment by picturepan2** [comment]
@alexbagirov The methods are same.

**Comment by aaron-bond** [comment]
I threw this together in case it helps someone understand what you mean. I hope it helps:
https://plnkr.co/edit/z45r86J0VfpWMhII5CKu?p=preview

:)

Also, I had to make some _tiny_ extra changes to get it all working right, so there might be some extra styles that could be brought into the library to facilitate it.

**Comment by picturepan2** [comment]
@Leva7 @aaron-bond has a good example for your need.

**Comment by niutech** [comment]
It is done in [my fork](https://github.com/niutech/spectre).
