### ISSUE TITLE
Compiler ignore Import Files from Source Folder

### ISSUE THREAD

**Issue by MkaaaaaaaY** [picturepan2/spectre#164]
Compiler = Koala

If i try to compile Spectre.css with my Compiler, the Compiler trys to compile the **src** Folder too.

Koala ignores files which start with an underscore.
Iam not sure but isnt it the same for other Compilers ?

**Comment by picturepan2** [comment]
Spectre uses Gulp for Less to CSS. The rules are defined in `gulpfile.js`.

**Comment by MkaaaaaaaY** [comment]
Okay.

**Comment by picturepan2** [comment]
@MkaaaaaaaY Now the import files are with underscore.
