### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by kaneschutzman** [picturepan2/spectre#166]
I was looking through to see what icons were included in the spectre.min.css file and it isn't clear, some of the code from the docs site do not work due to missing icons.  Are we expected to download Icomoons to use them?

**Comment by alexbagirov** [comment]
Yes, I have the same question. It seems that currently Spectre.css offers a mix of Google Material icons and something from Icomoon.

**Comment by picturepan2** [comment]
@kaneschutzman @alexbagirov Icons Spectre uses is Google's Material Design icon set, and the icon font is created by Icomoon. I use it for Spectre Docs only. I will explain more in the future.

**Comment by picturepan2** [comment]
Hi @kaneschutzman @alexbagirov and others. I have added pure CSS responsive icons to the Spectre.css https://picturepan2.github.io/spectre/elements.html#icons
