### ISSUE TITLE
[question] non-blocking modal

### ISSUE THREAD

**Issue by roemhildtg** [picturepan2/spectre#167]
Is it possible to create a non-blocking modal? One where the modal is displayed, but the content underneath would still be interact-able?

**Comment by picturepan2** [comment]
@roemhildtg Yes, you can just add `overflow-y: hidden;` to `body`.

**Comment by picturepan2** [comment]
@roemhildtg You mean Popovers?

**Comment by TigersWay** [comment]
That wouldn't be a model anymore, right?

**Comment by TigersWay** [comment]
Model..... Greer

**Comment by picturepan2** [comment]
<img width="391" alt="dropbox" src="https://cloud.githubusercontent.com/assets/126385/23889262/12901670-08c7-11e7-8a01-bd5c5c766b2b.png">
I take this Dropbox onboard tips as an example (It is a Popover).  Is it what you want?

**Comment by roemhildtg** [comment]
I'm actually trying to use the modal component, but allow users to click the content behind the modal.

**Comment by roemhildtg** [comment]
Basically I have a web map that displays info in a modal when the map is clicked. But I'd still like to be able to move the map when the modal is open

**Comment by picturepan2** [comment]
@roemhildtg Ahh, you can just remove the `modal` and `modal-overlay` divs and keep the `modal-container`. Use your JS to position `modal-container` div.

**Comment by roemhildtg** [comment]
Ahh, of course. That was easy.
