### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by kaneschutzman** [picturepan2/spectre#168]
Has anybody used a sticky footer with Spectre?  I've tried some common flexbox methods but can't get them to work, coupled with my limited flexbox knowledge it's becoming a tough problem to crack...

**Comment by picturepan2** [comment]
@kaneschutzman Do you mean the sticky footer in [Panels](https://picturepan2.github.io/spectre/layout.html#panels) ?

**Comment by kaneschutzman** [comment]
@picturepan2 Sorry I wasn't more specific.  I'm trying to achieve what is shown here [Codepen](http://codepen.io/chriscoyier/pen/RRbKrL) but I cannot get it to work.  Do you have a class already that can help with that?

**Comment by picturepan2** [comment]
@kaneschutzman In your case, you can also add `display: flex;` and `min-height: 100vh;` to the container. And add `flex: 1 0 auto;` to the body.
