### ISSUE TITLE
/dist folder in Github

### ISSUE THREAD

**Issue by alexandremjacques** [picturepan2/spectre#171]
Hi,

It isn't a best practice to commit the dist folder to the version control system. I would be nice if Gulp generate it only when running the gulpfile locally (and add this folder to .gitignore).

It's kind annoying since, to `git pull` the changes, git complains about having modified files in my local branch and blocks the pull.

I imagine you do that to facilitate distribution. But a separate web folder to serve the compiled files would be better.

Just my 2c.

**Comment by roemhildtg** [comment]
Another option would be to commit the dist folder to the gh-pages branch instead and use that for the documentation site.

**Comment by picturepan2** [comment]
Thanks. Any better choices?

**Comment by luminarious** [comment]
On the other hand, it's really nice to have the dist folder when I'm not actually building CSS with included tools, but rather including it in a bigger project that actually uses Stylus.

**Comment by picturepan2** [comment]
@alexandremjacques There are a number of people and people use NPM still want the compiled `dist` files. It is safe to overwrite `dist` folder when compiling LESS.

**Comment by alexandremjacques** [comment]
@picturepan2 the problem is not compilation. The problem remains in trying to `git pull` after having compiled locally. `git` complains saying that I have local changes. Again, it's just a minor annoyance but still a "bad practice" since `/dist` folders should be generated, not cloned.

**Comment by picturepan2** [comment]
@alexandremjacques The next plan is: making `/dist` ignored and precompiled CSS files in `/docs/dist` folder. Is it better?

**Comment by alexandremjacques** [comment]
Seems perfect! Great solution!!

*Alexandre Jacques*
alexandre.jacques@enabling.com.br
+55 11 95055.1377

**Comment by picturepan2** [comment]
@all I have changed the build process in v0.2.13 https://github.com/picturepan2/spectre/tree/0.2.13 , but not merge into `master` yet. You can have a review and give feedbacks. Thank you all.

**Comment by picturepan2** [comment]
@alexandremjacques [v0.2.13](https://github.com/picturepan2/spectre/releases/tag/v0.2.13) released. `/dist` dir is ignored.

**Comment by picturepan2** [comment]
@alexandremjacques DO you think [the importing SASS](https://picturepan2.github.io/spectre/getting-started.html#importing) is a better solution? 
Ignoring the `/dist` seems not good enough to people who don't read the Docs carefully.

**Comment by alexandremjacques** [comment]
@picturepan2 just look what others libraries are doing. They offer more than one way to download. If people want just the built version, use a CDN or download the compiled file from your site/github. Otherwise, if people want to clone the project, you should have the ‘/dist’ folder in the ‘.gitignore’.
