### ISSUE TITLE
wording

### ISSUE THREAD

**Issue by noclat** [picturepan2/spectre#172]
Hey, just a friendly issue to point out that the effect you call “parallax” should actually be named “perspective”. Parallax involves multiple layers moving at different speed. Perspective involves depth.

**Comment by picturepan2** [comment]
I think I would have added another layer of text. But no time yet.

**Comment by adaniello** [comment]
I had same doubt, but then i found that also Apple's official docs tell about "parallax": thus it's true, it need at least another layer to be complete.

**Comment by picturepan2** [comment]
@noclat I have added front layer to the Spectre Parallax https://picturepan2.github.io/spectre/experimentals.html#parallax.

**Comment by noclat** [comment]
Neat! :)
