### ISSUE TITLE
Center the dropdown relative to its toggle

### ISSUE THREAD

**Issue by Leva7** [picturepan2/spectre#175]
Right now, there are two options for positioning the dropdown:

- Default, aligned by the left edge
- `dropdown-right`, aligned by the right edge

But I want the dropdown to be aligned by the centre.  
There's one obvious solution to add a CSS property `left: ...px` that would move it to the center, but that requires hardcoding the pixel value and may not always be accurate. Is there a better way?

**Comment by adaniello** [comment]
Why not use a container and fix align simply with "margin:0 auto;"?
But all depends on your layout.

**Comment by adaniello** [comment]
A doubt: are you telling about "dropdown" component or its "menu"? Because "dropdown-right" fix only the menu position to prevent it appearing off screen.

**Comment by adaniello** [comment]
If you interested to center menu, you'ld try adding to `.dropdown .menu` class:

```
left: 50%;
transform: translateX(-50%);
```

**Comment by picturepan2** [comment]
@Leva7 @adaniello is right.
