### ISSUE TITLE
模态框在IE11中，不居中

### ISSUE THREAD

**Issue by ferqx** [picturepan2/spectre#177]
![qq 20170403101137](https://cloud.githubusercontent.com/assets/23183225/24593432/f4228670-1855-11e7-8e36-5398fd904bd6.png)

**Comment by picturepan2** [comment]
这部分的代码是怎样的呢？

**Comment by ferqx** [comment]
如果用IE11打开spectre官网然后点击模态框 也是不居中的

**Comment by picturepan2** [comment]
已经在 v0.2.12 中修复。 https://github.com/picturepan2/spectre/releases/tag/v0.2.12
