### ISSUE TITLE
导航栏部分，在谷歌当中是左对齐，但是IE11中却是两端对齐

### ISSUE THREAD

**Issue by ferqx** [picturepan2/spectre#178]
![qq 20170403101448](https://cloud.githubusercontent.com/assets/23183225/24593483/7c0ec9ae-1856-11e7-9e58-5cca83099fae.png)

**Comment by picturepan2** [comment]
这部分的代码是怎样的呢？

**Comment by ferqx** [comment]
和官网的Navbar是一样的，IE11打开官网也是一样的问题

**Comment by picturepan2** [comment]
已经在 v0.2.12 中修复。线上文档更新：https://picturepan2.github.io/spectre/layout.html#navbar。
