### ISSUE TITLE
spectre.css 全局设置了:focus，但是这样在IE11中点击div也会出现阴影层（box-shadow），希望这个做特定的限制

### ISSUE THREAD

**Issue by ferqx** [picturepan2/spectre#179]
:focus{
    box-shadow:0px 0px 0px 0.2rem rgba(0,188,212,0.15);
}

**Comment by picturepan2** [comment]
I will improve it in next version v0.2.12.

**Comment by picturepan2** [comment]
`:focus` support has been improved in https://github.com/picturepan2/spectre/releases/tag/v0.2.12. Only buttons and form components will have `:focus` shadows.
