### ISSUE TITLE
Toast class names confusing

### ISSUE THREAD

**Issue by ritz078** [picturepan2/spectre#185]
I mainly have 2 issues.

1. `.toast-danger` is somehow confusing. We don't use the word danger generally in coding. Most of the times it either `error` or `warning`.

2. I see there's only one present for warning i.e `toast-danger` (i assume its for warning). It would be great to have a separate class name for **error** thats a bit reddish and so there's a clear distinction between `warning` and `error`

**Comment by picturepan2** [comment]
@ritz078 Yes, `danger` naming is from the habit of Bootstrap. I think you are right. `error` is little confusing here.

**Comment by picturepan2** [comment]
@ritz078 In v0.2.13 https://github.com/picturepan2/spectre/pull/188 `danger` is renamed to `error`.
