### ISSUE TITLE
advanced form example.

### ISSUE THREAD

**Issue by faststare** [picturepan2/spectre#187]
any advanced form example that have positioning?

I'm trying to build a html form for web apps with your css framework but I have an alignment problem.

basically, I need a space in input box(horizontally) and I want the select tags(vertically) that are align to each other.

here's my code: https://plnkr.co/edit/AQVoucJcv2UPKEFB2FmY?p=preview

please help me or just give me an example for html form picturepan2.
tia

**Comment by picturepan2** [comment]
@faststare https://plnkr.co/edit/y9Xep5WmnI7zoyOhy0mj?p=preview Please look at this.

**Comment by faststare** [comment]
Thanks picturepan2.
