### ISSUE TITLE
Location of Dist Folder in latest NPM Package

### ISSUE THREAD

**Issue by Jcambass** [picturepan2/spectre#193]
The latest NPM Version of Spectre.css has the dist folder located in the docs folder. I believe this isn't on purpose?

EDIT: It is on purpose. May the docs should be updated to show this change ?

**Comment by alexandremjacques** [comment]
Yes. It is: #171

**Comment by picturepan2** [comment]
@Jcambass Yes, on purpose. And I am looking at https://docs.npmjs.com/files/package.json#files . Do you have better solution?

**Comment by roemhildtg** [comment]
When you do `npm publish` npm will zip up all the files in the directory, including files ignored by the `.gitignore`. Why not run the build before publish, so the dist folder is in the npm package, but not committed to the repository?

**Comment by picturepan2** [comment]
@roemhildtg I published v0.2.14 and I added `files` in package.json. It works now.
