### ISSUE TITLE
Collapse menu

### ISSUE THREAD

**Issue by totomakers** [picturepan2/spectre#195]
Can you provide a collapse menu option ?
Thanks for your great work 👍

**Comment by picturepan2** [comment]
@totomakers What collapse menu do you need?

**Comment by zusamann** [comment]
I think it could be an accordion which can also be used as a vertical menu.
See examples: 
https://semantic-ui.com/modules/accordion.html
http://bootsnipp.com/snippets/featured/accordion-menu

**Comment by totomakers** [comment]
Yes its that :) , usefull for sidebar layout with submenu :)

**Comment by totomakers** [comment]
Thx @picturepan2 👍  https://github.com/picturepan2/spectre/commit/771544f0ae6babd860466f51495746fcd31f3c03

**Comment by picturepan2** [comment]
@totomakers Is it what you need?
