### ISSUE TITLE
Sass port available

### ISSUE THREAD

**Issue by nusu** [picturepan2/spectre#196]
First of all I liked the simplicity of spectre, good job yan 👍 
I converted spectre to sass in order to people like me use however they want

repository:
https://github.com/nusu/spectre.scss

**Comment by picturepan2** [comment]
Thank you.

**Comment by antonioaguilar** [comment]
Really looking forward to this. Out of curiosity, @picturepan2 why did you write it in LESS?

**Comment by picturepan2** [comment]
@antonioaguilar Just because LESS is one of the easiest and workable solutions.

**Comment by rhukster** [comment]
FYI, I didn't know about this @nusu version, so I also ported the latest 0.2.14 version to SCSS.  I'm pretty sure this latest version is 100% in sync and compatible with the LESS version.

https://github.com/trilbymedia/spectre-scss

Gulp tasks are also updated to use SCSS, and it builds the same way as before. Compilation is crazy fast with libsass installed.

I've already synced and upgraded from 0.2.13 to 0.2.14 and it wasn't less painful than expected.  It would be **awesome** if you could move to SCSS going forward :)

**Comment by Turqueso** [comment]
@picturepan2 what are the too priority bugs before changing to sass? maybe they can be compiles in a project so we can help

**Comment by izcream** [comment]
im using bootstrap v4 but im on find new css framework and i interest in spectre but it's has only less version. I want SCSS version from official spectre is possible 😄  Thanks

**Comment by rhukster** [comment]
I was going to suggest using mine until the official SCSS version is made available by @picturepan2.  I'm going to keep it up to date with the releases.

**Comment by m5o** [comment]
💡 fyi, bootstrap folks created an [upstream converter](https://github.com/twbs/bootstrap-sass#upstream-converter) script time ago. The [`less_conversion.rb`](https://github.com/twbs/bootstrap-sass/blob/master/tasks/converter/less_conversion.rb) does most of the job, but don't look trivial on the first sight. /cc @rhukster

**Comment by rhukster** [comment]
BTW I've updated mine to 0.2.15 - #251

**Comment by picturepan2** [comment]
@ALL Spectre is in SASS since v0.4.0.

**Comment by gilbert** [comment]
Aw, LESS was the reason I chose Spectre in the first place a couple months ago. `node-sass` is a pain to install. Was there a reason to switch besides people asking for it?

**Comment by picturepan2** [comment]
@gilbert SASS function syntax is more clear than LESS. SASS community is larger and more active.
