### ISSUE TITLE
https://github.com/picturepan2/spectre/tree/master/dist returns 404

### ISSUE THREAD

**Issue by adtac** [picturepan2/spectre#197]
There's a link (https://github.com/picturepan2/spectre/tree/master/dist) on your README that's 404 now. Just thought you should know :)

Great framework, love it!

**Comment by nusu** [comment]
they took dist folder into docs:
https://github.com/picturepan2/spectre/tree/master/docs/dist

**Comment by picturepan2** [comment]
@adtac I am fixing it in next release.

**Comment by picturepan2** [comment]
@adtac I have merged the fix in the [v0.2.14](https://github.com/picturepan2/spectre/releases/tag/v0.2.14) release.

**Comment by adtac** [comment]
Cheers, thanks!

BTW I just used spectre in my latest project :) (check out https://github.com/adtac/commento)

**Comment by picturepan2** [comment]
@adtac Cool. 👍 Any feedback is welcome.
