### ISSUE TITLE
Force tooltip font

### ISSUE THREAD

**Issue by mtancoigne** [picturepan2/spectre#200]
For now, the toolptips inherits the element's font, so it breaks when we use it on a custom element (a fontawesome icon, i.e.). Forcing the font in the tooltip may avoid this kind of behavior.

**Comment by Anachron** [comment]
I am not sure if we should be fixing custom elements if spectre doesn't provide any...

**Comment by mtancoigne** [comment]
That's true in a way, but in another, we expect the tooltips to have always the same look and feel, so if one use it on an element with a different font, the tooltip should keep its oroginal font (let's say, a tooltip on a `<code>` element)...

**Comment by picturepan2** [comment]
@mtancoigne Yes, there is supposed to have a reset for tooltips to remove effects from the parents.  There are 2 issues I am thinking. One is [the Asian fonts support](https://github.com/picturepan2/spectre/blob/master/src/asian.less). Another is using [LESS extend function](http://lesscss.org/features/#extend-feature) to make CSS smaller.

**Comment by mtancoigne** [comment]
In the PR, I only added `font-family: @body-font-family;`, but you're right for asian support...
Maybe this is the solution... 
```less
.cjk,
.cjk .tooltip {
  font-family: @cjk-font-family;
}
```
And wich class do you want to extend ? Because you're right, the font family isn't the only property to force, there's also the weight, decoration, color, etc...

**Comment by picturepan2** [comment]
@mtancoigne Yes, `font-family` is only one part of the whole reset styles. And all elements with `::before` and `::after` have this issue. Use LESS extend function can reuse the code as many as possible.

**Comment by picturepan2** [comment]
@mtancoigne Do you think wrapping your Font Awesome icons with `<span>` or `<i>` inside `.tooltip` is a good idea?
(There are too much style reset to add.)

**Comment by mtancoigne** [comment]
@picturepan2 Yes, I think that's a good workaround, which should be noted in the docs.

**Comment by mtancoigne** [comment]
There is the same issue with font sizes and popovers: a popover with a big trigger  will create a big popover too.
