### ISSUE TITLE
Overflow handling in <table>

### ISSUE THREAD

**Issue by AdamDomafoldi** [picturepan2/spectre#202]
Hi,

The responsive table works well with notebooks/tablets but when it comes to mobile, there is an overflow. I think something like `overflow : auto` could solve the problem. It would be really nice to scroll vertically, too, the table like in Bootstrap. I have 10 columns in my table at the moment.

B.R.

Adam

**Comment by picturepan2** [comment]
@AdamDomafoldi To make it a fully responsive table, you will need to add a wrapper outside table and make the wrapper `overflow: auto;`. I will add the example in the Docs soon.

**Comment by AdamDomafoldi** [comment]
@picturepan2 Thanks, it solved my problem. You should definitely add this example to the Docs.

Keep up the good work!

B.R.

Adam
