### ISSUE TITLE
Auto-Update website with latest version?

### ISSUE THREAD

**Issue by Anachron** [picturepan2/spectre#203]
Is it possible to either update the website with every push or create a subpage (latest/beta) with the latest version?

**Comment by picturepan2** [comment]
@Anachron Do you mean auto-update your website with every new Spectre.css release?

**Comment by Anachron** [comment]
Not my website, but the spectre.css one when you release a new version.

**Comment by Anachron** [comment]
This one: https://picturepan2.github.io/spectre

**Comment by picturepan2** [comment]
@Anachron Yes. The Spectre Docs updates automatically with `master` branch. Btw, do you notice anything wrong? You can tell me by a new issue or Pull Request. Thank you.

**Comment by picturepan2** [comment]
@Anachron Do you notice any issue?

**Comment by Anachron** [comment]
Oh right you sync with master, not with latest tag, I see. All good, you can close this!
