### ISSUE TITLE
Focus dotted border around Links

### ISSUE THREAD

**Issue by indivisable** [picturepan2/spectre#209]
I am trying to remove the border around links when using Spectre, these happen when you focus on the links with Tab Key or click on mouse, it is rather annoying when it is around image links.

![image](https://cloud.githubusercontent.com/assets/22860891/25515009/1f297fcc-2ba7-11e7-8130-344ff32eac4f.png)

I have tried almost all the ways I could think of to remove but cannot seem to track it down. It does it only in Chrome it seems (latest), as it does not do same in Safari.

```
    img:focus {
    	outline: none !important;
    	outline: 1px solid transparent !important;
    }
    
    a:active, a:focus, {
    	outline: none !important;
    	border: none !important;
    	-moz-outline-style: none !important;
    	outline: 1px solid transparent !important;
    }
    
    a img {
    	outline: 1px solid transparent !important;
    }
    
     :link:focus, :visited:focus {
    	outline: 1px solid transparent !important;
    }
    
     :focus {
    	outline: 1px solid transparent !important;
    }
    
    a:active {
    	outline: none !important;
    	outline: 1px solid transparent !important;
    	outline: medium none !important;
    }
    
    button::-moz-focus-inner, input::-moz-focus-inner {
    	border: 0;
    	padding: 0;
    }
   
     :focus {
    	outline: medium none !important;
    }
    
     :active {
    	outline: medium none !important;
    }
    
    a {
    	outline: medium none !important;
    }
    
    *:active, *:hover, *:focus {
    	outline-width: 0!important;
    	outline: medium none !important;
    	outline: 1px solid transparent !important;
    }
    
    a, a:active, a:focus, button, button:focus, button:active, .btn, .btn:focus, .btn:active:focus, .btn.active:focus, .btn.focus, .btn.focus:active, .btn.active.focus {
    	outline: none;
    	outline: 0;
    }
    
    input::-moz-focus-inner {
    	border: 0!important;
    	outline: 1px solid transparent !important;
    }
    
    :focus {
    	box-shadow: none !important;
    }

```
Any ideas?

Might be related: http://stackoverflow.com/questions/11173338/outlinenone-is-not-working-on-input-tags

**Comment by picturepan2** [comment]
@indivisable Hi, Spectre uses `box-shadow` for :focus state. You can modify the `.control-shadow()` mixin in `src/mixins.less` or just remove the box-shadow of `a:focus` in `src/base.less` .

**Comment by indivisable** [comment]
This fixed it! Thanks very much... was driving me a bit crazy trying to override without touching the framework.

<3 spectre a lot, great job :)

**Comment by picturepan2** [comment]
@indivisable I do this because of Accessibility. Focus state is very important for keyboard and sight related problem users.
