### ISSUE TITLE
[Feature request] Danger toast?

### ISSUE THREAD

**Issue by Rurik19** [picturepan2/spectre#21]
It would be useful to have separate toasts for success and errors

**Comment by picturepan2** [comment]
There were some additional toasts colors, like Bootstrap provides. But later I removed those. So only success and danger toasts are needed? any other ones?

**Comment by Rurik19** [comment]
Basically, yes, these two (in addition to gray and primary)

**Comment by geoffdavis92** [comment]
Also, perhaps adding an inverted `.btn-clear` to darker (ie `.toast-primary`) toasts.

**Comment by picturepan2** [comment]
@geoffdavis92 Yes, I am improving the button.

**Comment by picturepan2** [comment]
Improved in https://github.com/picturepan2/spectre/pull/26
