### ISSUE TITLE
Suggestion: dropdown with search

### ISSUE THREAD

**Issue by tu5** [picturepan2/spectre#210]
For first: wow! contratulations! spectre seem to be a really nice piece of code :)
My suggestion is to add a dropdown with search like here https://semantic-ui.com/modules/dropdown.html scroll to (search selection). Though I'm not sure if it's even possible with CSS, but spectre shows that everything seems possible :+1:

**Comment by aaron-bond** [comment]
I think your need is https://picturepan2.github.io/spectre/components.html#autocomplete
You'd need to combine that with some JS in order to facilitate the data backing the drop down though. AFAIK there's no way to link up a `<select>` with a textbox outside of JS.
