### ISSUE TITLE
Form input types: date field doesn't show button to open the calendar.

### ISSUE THREAD

**Issue by cydside** [picturepan2/spectre#215]
Hi,
I tested form input date successfully on chromium(Version 58.0.3029.9) but it seems to not work properly on firefox 53.0 (64 bit).

Thanks in advance,

Danilo

**Comment by adaniello** [comment]
Spectre haven't button or plugin for datetime input fileds.
Firefox don't support date and time input types. See at http://caniuse.com/#feat=input-datetime

**Comment by adaniello** [comment]
You should use your datepicker plugin.

**Comment by cydside** [comment]
Thanks.
