### ISSUE TITLE
Is there any roadmap of the project?

### ISSUE THREAD

**Issue by elias-garcia** [picturepan2/spectre#216]
Hi, I've been following Spectre for a long time and now I'm starting to use it in some Angular projects (it doesn't have any js, so it's awesome!).

I'm creating a lot of reusable Angular components and my idea is to share it in a Github repo in the near future, but it would be very advantageous to know the the future project plans, the status of the experimental components and the changes planned for their new versions etc.

I searched trough the documentation and this Github repo but I didn't find any roadmap or any file containing the plans for the future. It would be nice to have a Github project associated like Twitter does (https://github.com/twbs/bootstrap/projects/2). This can be a very important enhancement for the project I think!

**Comment by picturepan2** [comment]
Thank you. I will make use of the GitHub Projects.

**Comment by tobi-or-not-tobi** [comment]
@elias-garcia did you manage to create the repo? I'm starting to use this lib in angular as well and I would need components soon. My first requirement would be to add a custom version easily, ideally using a config file. Any thoughts about that?

**Comment by elias-garcia** [comment]
@tobi-or-not-tobi I didn't have time yet... I created some components but adapted to a project I made... What do you mean by "adding a custom version easily"?

**Comment by tobi-or-not-tobi** [comment]
If I use spectre.css in a project, I'd like to simply add it to my package.json dependencies, install and go. Then, if I need to have a different color scheme or anything, it would be great to have an option to do that in a project specific file. The way it works now - but correct me if i'm wrong - is that I need to create a custom version of spectre.css and include the compiled results in my project.
