### ISSUE TITLE
offset is not available?

### ISSUE THREAD

**Issue by GabMic** [picturepan2/spectre#217]
If i want to make an offset in the grid, how can i do that? 
for example, col-md-8 offset-2.
Thanks.

**Comment by leroydev** [comment]
The way I'm currently doing it is just creating an empty column that will function as offset. Example:
```
<div class="columns">
    <div class="column col-2"></div>
    <div class="column col-8 col-sm-12">
        <!-- Content in here -->
    </div>
</div>
```
Which will lead to `2` offset on screensizes larger than `sm`.

**Comment by RuinSain** [comment]
well, that's a bummer! it's a simple and crucial thing in a grid. hope it will be added! this can ba a great update to the framework.

**Comment by leroydev** [comment]
@picturepan2 Is there an 'official' way to create offset columns or is the workaround I proposed the only way for now?

**Comment by picturepan2** [comment]
@leroydev Empty column is the only way for now.

**Comment by picturepan2** [comment]
@RuinSain Spectre provides some [basic offset classes](picturepan2.github.io/spectre/layout.html#grid-offset) like Bootstrap does. Do you think these are enough for you?

**Comment by picturepan2** [comment]
@leroydev I add [basic offset classes](https://picturepan2.github.io/spectre/layout.html#grid-offset) which provides auto offset and you don't need to add empty columns.

**Comment by davestewart** [comment]
I've proposed SCSS for responsive grid offsets here: #566.
