### ISSUE TITLE
Col size small, medium, large

### ISSUE THREAD

**Issue by mgohin** [picturepan2/spectre#22]
Hi,

can I choose `col-` depending on screen size like in Bootstrap or Foundation ?

I don't want the same % of width on mobile and desktop.

**Comment by picturepan2** [comment]
I am doing this right now in a new branch. 👍

**Comment by mgohin** [comment]
Holy crap, that's fast ! 👍

**Comment by mgohin** [comment]
Any chance to get an option like `small-hide` `small-show` ?
Same for medium, large ?

I'll allow us to show/hide thing depending on screen size ?

**Comment by picturepan2** [comment]
There are some `hide` utilities in `src/utilities.less`. Still working on more responsive things.

**Comment by mgohin** [comment]
will check that

**Comment by picturepan2** [comment]
Please check `feature/add-responsive-grid` branch. I updated the doc as well. Thanks.

Though I add more col-xs-, col-sm- and col-md- options, another responsive thing form-horizontal is broken. I will fix it.

**Comment by mgohin** [comment]
seems to be working well ! Will you merge it soon ? Can't tell npm to use a branch I guess ^^

**Comment by mgohin** [comment]
About the hide thing, in utilities there is nothing about hide/show in xs, sm (etc)

**Comment by mgohin** [comment]
looks like I didn't check enough :

    @media screen and (max-width: 480px) {
    .hide-xs {
        display: none !important;
        }
    }

**Comment by mgohin** [comment]
But missing same thing for show-xs etc

**Comment by picturepan2** [comment]
Sorry, it is in `src/layout.less`.

**Comment by picturepan2** [comment]
Merged. https://github.com/picturepan2/spectre/pull/23

**Comment by picturepan2** [comment]
@mgohin Sorry, no `show-` related classes yet. Still considering.

**Comment by mgohin** [comment]
It's very usefull to display something elsewhere depending on screen size
