### ISSUE TITLE
Fixed Width Layout

### ISSUE THREAD

**Issue by chauhankiran** [picturepan2/spectre#222]
I am planning to use `spectre.css` in one of my side project. The problem that currently I am facing is, with fixed-width container. Do we have fixed width container? From the documentation I only seen `container` with full width.

I found that you are using something called .grid-960 but not sure of it usage.

**Comment by picturepan2** [comment]
@chauhankiran Yes, `container` is full width container. You can use `grid-1280`(1280px inside), `grid-960`(960px inside) and `grid-480`(480px inside) for different fixed width container.

**Comment by picturepan2** [comment]
@chauhankiran Latest version 0.2.15 is released. I have updated the [responsive container docs here](https://picturepan2.github.io/spectre/layout.html#responsive).
