### ISSUE TITLE
Code snippet plugin

### ISSUE THREAD

**Issue by aaron-bond** [picturepan2/spectre#224]
Sorry to raise this as an issue - I was just wondering what plugin was used to create the code snippets in the documentation (unless they're coded by hand?)

It would be good to know what plugin generates the snippets with the right classes / structure to match the CSS.

P.S. I wasn't sure how else to ask a question. Perhaps we should start a [Gitter channel](https://gitter.im) for Spectre.css?

**Comment by picturepan2** [comment]
@aaron-bond I Yes, they are coded by hand. There are some tools or js to highlight code, but these examples are easy.
Maybe Slack?

**Comment by aaron-bond** [comment]
Slack would be good. 
I might build out a demo app with Angular/Spectre/sendbird.com if I get some time... :P
