### ISSUE TITLE
[Suggestion] Allow text on top of meter

### ISSUE THREAD

**Issue by henrycjc** [picturepan2/spectre#225]
A nice feature would be the ability to have text appear in/on the `<meter>` tag. So for example, you could write the progress in plain text in addition to the visual aid. 

Example http://jsfiddle.net/qfwTy/

**Comment by picturepan2** [comment]
@henrycjc You can use [Bars](https://picturepan2.github.io/spectre/components.html#bars) instead of native `Meter`which is very hard to custom. The style of `Meter` only applies to Chrome.
