### ISSUE TITLE
作者的设计方向非常不错，希望能快点更新版本

### ISSUE THREAD

**Issue by ferqx** [picturepan2/spectre#227]
能不能多加点颜色呢？比如按钮的颜色，感觉不够用呢

**Comment by picturepan2** [comment]
@ferqx 比如哪些按钮颜色？

**Comment by ferqx** [comment]
就是平常的button按钮，当然也希望 a-link 按钮 点击的时候不用带边框或阴影，因为放在导航栏上的话，点击并不好看

**Comment by puny-d** [comment]
Also hope more colors on buttons~~
我看到pull request有人提交了更多的按钮颜色&拖拉样式框，希望早日合并到新版本中

**Comment by picturepan2** [comment]
@puny-d @ferqx 嗯，还在纠结需要哪些颜色，你们觉得可以增加哪些颜色按钮呢？按重要度排序一下，谢谢。

**Comment by puny-d** [comment]
@picturepan2 ，我觉得黑色、警告色（黄色）、红色都可以的~

**Comment by picturepan2** [comment]
@ferqx 增加了成功和错误按钮。文档：https://picturepan2.github.io/spectre/elements.html#buttons 。
