### ISSUE TITLE
I think <section> is being used improperly

### ISSUE THREAD

**Issue by tomcam** [picturepan2/spectre#231]
I LOVE Spectre.css! Thank you. 

I think maybe the &lt;section&gt; is being used in a way that may not be optimal for HTML. According to [MDN](https://www.w3.org/wiki/HTML/Usage/Headings/h1only), a  &lt;section&gt; tag:

- Should be identified by a child heading tag
- Should not be used as a generic container;  &lt;div&gt; serves that purpose
- Should be replaced by &lt;article&gt;  if it makes sense to syndicate its contents separately

I have been replacing &lt;section&gt;  tags with  &lt;div&gt;  accordingly and it seems to work fine for the most part. It also reduces warnings when I validate the HTML.

Can you tell me if these examples look OK with revised use of  &lt;div&gt; in place of  &lt;section&gt;?

starter-template.html [GitHub source](https://github.com/tomcam/spectre-css-examples/blob/master/starter-template.html), [preview](https://htmlpreview.github.com/?https://github.com/tomcam/spectre-css-examples/blob/master/starter-template.html)

layout1.html [GitHub source](https://github.com/tomcam/spectre-css-examples/blob/master/layout1.html), [preview](http://htmlpreview.github.io/?https://github.com/tomcam/spectre-css-examples/blob/master/layout1.html)

update1.html [GitHub source](https://github.com/tomcam/spectre-css-examples/blob/master/update1.html), [preview](http://htmlpreview.github.io/?https://github.com/tomcam/spectre-css-examples/blob/master/update1.html)

**Comment by picturepan2** [comment]
@tomcam It is fine to use `<section>` for a document part, not a webpage layout section. `<section>` also requires heading titles. 

I have replaced `<section>` with `<div>` in some part of the Docs. Thank you.
