### ISSUE TITLE
What is the code for Filters

### ISSUE THREAD

**Issue by jaywick** [picturepan2/spectre#232]
There doesn't seem to be any code in the docs regarding [Fiters](https://picturepan2.github.io/spectre/experimentals.html#filters)

**Comment by Coolnesss** [comment]
You can check the page source, e.g in your browser URL bar: view-source:https://picturepan2.github.io/spectre/experimentals.html#filters

**Comment by picturepan2** [comment]
@jaywick I added [Filters code](picturepan2.github.io/spectre/experimentals.html#filters) in the Docs. Hope it helps.
