### ISSUE TITLE
Multiple tags in filters

### ISSUE THREAD

**Issue by Coolnesss** [picturepan2/spectre#233]
Hey, really cool framework, thanks a lot for making it.

My question is, is it possible to have the pure css tag-filtering as shown [here](https://picturepan2.github.io/spectre/experimentals.html#filters) for multiple tags per resource?

On a related note, if I try to add my own tags the filter doesn't work for those tags. Here's a gist to illustrate https://gist.github.com/Coolnesss/6792f3a43553ab3d1d038f459a791330

EDIT: had a look [here](https://github.com/picturepan2/spectre/blob/master/src/filters.less) and I understand how the filters work now. Wish there was an example available on the page to avoid the confusion :) feel free to close, might be useful for future reference.

**Comment by picturepan2** [comment]
@Coolnesss Because the Filters component is an experimental one. It is not fully documented. I will do it after fixing other bugs. 
Thank you.

**Comment by Coolnesss** [comment]
Hey,

That's great, thanks.
