### ISSUE TITLE
Question: media queries and mobile devices

### ISSUE THREAD

**Issue by prologic** [picturepan2/spectre#234]
Can someone explain how the various media queries and responsive grid classes work for managing content/views on different screen sizes to someone that's a complete n00b at CSS? Please :)

**Comment by picturepan2** [comment]
@prologic Sorry, I almost missed this question. You can read this article on Smashing Mag https://www.smashingmagazine.com/2010/07/how-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website/ .

**Comment by prologic** [comment]
Thanks! I'll have a read!
