### ISSUE TITLE
Tooltip on icon issue

### ISSUE THREAD

**Issue by oliverjrose99** [picturepan2/spectre#235]
I found an issue with the tooltips when placed on icons. The text dosnt't show but there is a small box with the correct color and position.

[https://codepen.io/oliverjrose99/pen/zzyvop?editors=1100](https://codepen.io/oliverjrose99/pen/zzyvop?editors=1100)

**Comment by picturepan2** [comment]
@oliverjrose99 Because Icons and Tooltips both use `::before` and `::after` trick. It is a bug and I will think about how to fix it.

**Comment by picturepan2** [comment]
@oliverjrose99 It works only when you add Tooltips in the `has-icon-left` div, which is the wrapper of the form-input and icons. Is this perfect for your scenario?
