### ISSUE TITLE
default z-index(es) why are they so high?

### ISSUE THREAD

**Issue by prologic** [picturepan2/spectre#237]
See: https://github.com/picturepan2/spectre/blob/master/src/variables.less#L68

These seem to be really high for `@z-index-1` and above where things like simplemde assume single digit z-index(s)

See also sparksuite/simplemde-markdown-editor#610

**Comment by picturepan2** [comment]
@prologic I choose these z-index values because they are more flexible to add another z-index between any two of those. Sometimes we need to settle new layers with existing ones.

I close this issue and you can reopen it anytime you have a new z-index issue.

**Comment by prologic** [comment]
Thanks!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
