### ISSUE TITLE
Website Suggestion: Flexbox Grid Demo Boxes Are Very Difficult To See

### ISSUE THREAD

**Issue by skilfullycurled** [picturepan2/spectre#240]
Thank you for this wonderful, tiny, simple, but still beautiful framework!

A thought:  Perhaps it's just me but I find the [flexbox grid demo](https://picturepan2.github.io/spectre/layout.html#grid) exceedingly difficult to see.  I have to turn the contrast on my monitor down to zero just to begin to make out the boxes.  

Two ideas: 1) while this would ruin the grammer of the theme, the color of the boxes could be changed from "background" (#f8f9fa) to "gray light" (#e7e9ed).  2) Or, add a border around the boxes?

Again, many thanks for your work!

**Comment by picturepan2** [comment]
@skilfullycurled Spectre.css Docs updated with improved design. https://picturepan2.github.io/spectre/layout.html#grid Thank you.
