### ISSUE TITLE
more button color

### ISSUE THREAD

**Issue by bahirul** [picturepan2/spectre#241]
It will be nice add btn-error, btn-warning, and btn-info.

**Comment by bahirul** [comment]
@picturepan2 any idea ?

**Comment by picturepan2** [comment]
@bahirul When do you need a success and a info button?
btw, I built in a button mixin in it already. (https://picturepan2.github.io/spectre/getting-started.html#variables-buttons) .

**Comment by picturepan2** [comment]
@bahirul I only added success and error buttons in v0.4.7. If you need more, you can create yours with [button mixins](https://picturepan2.github.io/spectre/getting-started.html#variables-buttons).
