### ISSUE TITLE
offset grid

### ISSUE THREAD

**Issue by chick4nnn** [picturepan2/spectre#244]
I want "offset" grid layout same bootstrap

**Comment by picturepan2** [comment]
@chick4nnn Grid Offset is added in [v0.3.1](https://github.com/picturepan2/spectre/releases/tag/v0.3.1). You can learn more in [the Docs](https://picturepan2.github.io/spectre/layout.html#grid-offset).

**Comment by davestewart** [comment]
I've proposed SCSS for responsive grid offsets here: #566.
