### ISSUE TITLE
More docs

### ISSUE THREAD

**Issue by bartrylant** [picturepan2/spectre#245]
I noticed not everything that is in the less files, is documented. E.g. I found a class called "grid-1280". It's obvious what this does, but I was surprised this was not mentioned in the docs. Are there other hidden gems?

**Comment by picturepan2** [comment]
@bartrylant There is not many hidden things. [`Responsive container`](https://picturepan2.github.io/spectre/layout.html#responsive) has been updated.

**Comment by picturepan2** [comment]
@bartrylant I am trying to document the details as many as possible in every release. You can always check out Changelog.md to see updates.
