### ISSUE TITLE
Support has-error and is-error classes on checkboxes

### ISSUE THREAD

**Issue by resurtm** [picturepan2/spectre#246]
Hello!

Shouldn't checkboxes also support `has-error` and `is-error` classes? For example:

```html
<div class="form-group has-error">
	<label class="form-checkbox">
		  <input type="checkbox"/>
		  <i class="form-icon"></i>
		  I confirm agreement with <a href="#">Terms of Services</a>
	</label>
</div>
```

![image](https://user-images.githubusercontent.com/100198/28824274-2730e250-76e3-11e7-9de1-672ba5feca19.png)

The result checkbox should somehow have error state.

Cheers!

**Comment by picturepan2** [comment]
@resurtm Version 0.2.19 is released. Error and success states have been added to checkbox, radio and switch. https://picturepan2.github.io/spectre/elements.html#forms
