### ISSUE TITLE
Tabs control planned? Do, uh, I have to create them?

### ISSUE THREAD

**Issue by tomcam** [picturepan2/spectre#247]
I need tab controls with spectre.css. As far as I can tell, the only thing close to tabs would be filters, which really aren't the same. Do you plan to do tab controls? I would be happy to give it a try and attempt a PR, but I trust you way more than me to do a good job! I would even be happy to discuss paying you to do it. Love Spectre.css!

**Comment by picturepan2** [comment]
@tomcam There is Tabs component https://picturepan2.github.io/spectre/components.html#tabs.
