### ISSUE TITLE
[Feature Request] Off Canvas / Aside Menu

### ISSUE THREAD

**Issue by ryanmortier** [picturepan2/spectre#248]
This framework is amazing. I'm glad I came across it. The only feature that I think it's missing is an `off canvas` component.

**Comment by picturepan2** [comment]
@ryanmortier Released with 0.4.2 version. The Docs is here: https://picturepan2.github.io/spectre/experimentals.html#off-canvas .

**Comment by ryanmortier** [comment]
You're amazing! Thanks.
