### ISSUE TITLE
margin utilities have padding instead of margin

### ISSUE THREAD

**Issue by mohd-akram** [picturepan2/spectre#250]
Could you also possibly add `m-0`, `mt-0`, `p-0`, `pt-0`, etc.?

**Comment by picturepan2** [comment]
@mohd-akram fixed. m-0 = margin: 0; right?

**Comment by mohd-akram** [comment]
Yeah.

**Comment by picturepan2** [comment]
@mohd-akram v0.3.1 is released [release note](https://github.com/picturepan2/spectre/releases/tag/v0.3.1). `m-0` and `p-0` have been added.
