### ISSUE TITLE
Unofficial SCSS version updated to 0.3.2

### ISSUE THREAD

**Issue by rhukster** [picturepan2/spectre#251]
I've merged all the 0.3.2 additions/fixes/changes into my SCSS fork of Spectre.css: https://github.com/trilbymedia/spectre-scss

I've eyeball tested the docs with the LESS compiled version with the SCSS version and I'm pretty sure everything lines up 100%.  Please leave any issues you find on the repo above so as not to clutter the official repo with SCSS related inconsistencies.

I'll keep track of any updates like last time.  Still hoping we can have an official SCSS version added to the original repo some time :)

**Comment by picturepan2** [comment]
@rhukster Thank you so much. I will add SCSS version after fixing known bugs.

**Comment by natecox** [comment]
@picturepan2 Is there a timeline estimate for releasing an SCSS version of the library? I'm considering starting a new site with Spectre; however, I notice that since this release there is already a new minor version release (from 0.2.15 to 0.3.1).

**Comment by huangbong** [comment]
@rhukster can you update your repo to v0.3.1? It fixes #250 in mixins.

**Comment by rhukster** [comment]
Yes, I saw the release yesterday and I will fix it tomorrow.

**Comment by rhukster** [comment]
This has now been updated to the latest 0.3.1.  Please let me know if you find any inconsistencies.

**Comment by rhukster** [comment]
Updated original title/comment to reflect 0.3.2 release

**Comment by rhukster** [comment]
Looks like 0.4.0 might be a native scss release 👍 Looking forward to not having to merge these everytime :)

**Comment by huangbong** [comment]
@rhukster thank you boss man!

**Comment by picturepan2** [comment]
@rhukster Yes, thank you for all these works. v0.4.0 is coming soon.

**Comment by picturepan2** [comment]
v0.4.0 is released. 👻
