### ISSUE TITLE
h1-h6 font-size are too large in v0.2.16

### ISSUE THREAD

**Issue by gera2ld** [picturepan2/spectre#253]
In v0.2.16, the `font-size` of `<html>` is changed from `10px` to `20px`, but that of `<h1>`-`<h6>` is not changed, as a result, all heading tags become twice as large as before.

**Comment by picturepan2** [comment]
@gera2ld No, it is smaller than before. `H1` was 50px and it is 40px now.

**Comment by gera2ld** [comment]
Sorry, my fault, looking into a wrong branch.
