### ISSUE TITLE
Responsive spectre: Full width columns on small devides

### ISSUE THREAD

**Issue by reza-irdev** [picturepan2/spectre#254]
Hi,
How i can set my columns to be full width when i am on small screen?
For an example see image:

![t1](https://user-images.githubusercontent.com/12220097/29399872-79eb2da0-831a-11e7-88d3-bc62b62d99ea.png)

**Comment by picturepan2** [comment]
@reza-irdev You can add `col-xs-12` to have 100% width column when window is smaller than or equal to 480px.

For more Responsive layout, you can view [the Docs here](https://picturepan2.github.io/spectre/layout.html#responsive).

**Comment by reza-irdev** [comment]
@picturepan2 OMG! spectre!. Thank you for your fast and complete answer.  I do not know how I didn't see it ;-)
