### ISSUE TITLE
Should mark v0.2.15 as major update

### ISSUE THREAD

**Issue by ostoc** [picturepan2/spectre#257]
Because of the root font-size changed, will may affect REM based design. People need to be notified.

**Comment by huangbong** [comment]
Also when is v0.2.16 coming out? I feel like there should be a hotfix cause I need the margin mixins to work. (See https://github.com/picturepan2/spectre/commit/e1889c840e060b51e4b551a3e30f142ce4b9ec2b). It's a pretty big bug.

**Comment by picturepan2** [comment]
Today or tomorrow. I am adding some other fixes to it. Thank you.

Yan Zhu
________________________________

**Comment by picturepan2** [comment]
@ostoc Is it better to upgrade to 0.3.x branch?

**Comment by ostoc** [comment]
@picturepan2 from my experience the new REM is not compatible with old version, and I spend few hours to change my all REM in the whole project. I am up for 0.3.x branch :)

**Comment by picturepan2** [comment]
@ostoc Sorry for that. I learn a lesson from this update.
Do you think there is a way to upgrade this kind of core things without making any trouble to others? Any better place for publishing the important change?

**Comment by picturepan2** [comment]
I am making the next release: v0.3.1.

**Comment by picturepan2** [comment]
@huangbong v0.3.1 is released https://github.com/picturepan2/spectre/releases/tag/v0.3.1. The utilities bug has been fixed.

**Comment by huangbong** [comment]
@picturepan2 awesome! thanks! can you publish to npm? :)

**Comment by huangbong** [comment]
I really should be maintaining my own version but I'm too lazy right now lol. Appreciate the fast turnaround!

**Comment by picturepan2** [comment]
@huangbong Publishing. The bad network connection in Starbucks.

**Comment by picturepan2** [comment]
@huangbong Done.

**Comment by huangbong** [comment]
@picturepan2 FYI, the builds on cdnjs don't have the margin fix in. It's still padding. https://cdnjs.com/libraries/spectre.css

**Comment by dgdavid** [comment]
Hi @picturepan2 

>  Any better place for publishing the important change?

What about [keep a changelog](http://keepachangelog.com)? ;)

BTW, great job. Thanks a lot.

**Comment by picturepan2** [comment]
@dgdavid Thank you. I will look on that soon.

**Comment by jooldesign** [comment]
The dist/spectre.css file needs regenerating to include the margin/padding utility fix

**Comment by picturepan2** [comment]
@jooldesign Trying to fix it again.

**Comment by picturepan2** [comment]
@jooldesign Successfully updated with [v0.3.2](https://github.com/picturepan2/spectre/releases/tag/v0.3.2).
