### ISSUE TITLE
AMP support

### ISSUE THREAD

**Issue by niutech** [picturepan2/spectre#258]
Spectre could be compatible with [AMP](https://www.ampproject.org/) by slightly modifying the code: removing `!important`, replacing `<img>` with `<amp-img>` and removing inline `style=""` from HTML. I made the AMP components page demo: https://repl.it/KPR2/3 or fullscreen: http://s.cssdeck.com/labs/full/x5pjudqw/noframe

Would you like to add an official AMP flavor of the Spectre CSS framework?

**Comment by krlklm** [comment]
Why i would not promote AMP:

https://daringfireball.net/linked/2017/05/20/gilbertson-amp

**Comment by niutech** [comment]
I don't get that hatred for AMP. Of course one can make a performant website without it, but in the real life almost all companies bloat their websites. AMP is a radical step to forbid web bloat and stick to lightweight solutions. Furthermore it is open source.

**Comment by picturepan2** [comment]
@niutech I will not add an AMP flavor.

**Comment by niutech** [comment]
Finally I have made an AMP version of your framework: https://github.com/niutech/amp-spectre/

**Comment by leeoniya** [comment]
https://news.ycombinator.com/item?id=14695268

**Comment by niutech** [comment]
@AdsonCicilioti I generated AMP Spectre using this file: https://github.com/picturepan2/spectre/blob/master/dist/spectre.min.css
@leeoniya AMP v0.js is only 78.4 KB gzipped and it's served from the CDN, so it's downloaded only once for all AMP pages.

**Comment by AdsonCicilioti** [comment]
@niutech, the show/hide layout utility class din't work on elements with display:flex, like as navbar-sections.
