### ISSUE TITLE
Search box has a border to the right, separating it from search button

### ISSUE THREAD

**Issue by euantorano** [picturepan2/spectre#260]
As can be seen in the screenshot in [this pull request using Spectre](https://github.com/FedericoCeratto/nim-package-directory/pull/3), it looks like the search box has a subtle grey border to the right separating it from the search button. This looks a little odd to me.

**Comment by picturepan2** [comment]
@euantorano it is fixed in [v0.3.2](https://github.com/picturepan2/spectre/releases/tag/v0.3.2).
