### ISSUE TITLE
drop down doesn't work on safari on IOS

### ISSUE THREAD

**Issue by Jped** [picturepan2/spectre#263]
I have a dropdown on the mobile version of [themorningmunch.com](https://themorningmunch.com) (you have to sign in to see it)

The dropdown button doesnt work with IOS. I have tested it on my android phone and it does work
I have read online that there are similar problems to this on bootstrap, is there any solution for spectre?

here is the code for the dropdown
```
  <div class="dropdown">
              <button  style="margin-right:10px" href="#" class="btn dropdown-toggle" tabindex="0">
                  <i class="icon icon-more-vert"></i>
              </button>
        <!-- menu component -->
              <ul class="menu" style="text-align:center">
                <li><a href="/viewMunch">Your&nbsp;MM </a></li>
                <li><a href="/editOrder"><span class="lg-view"> Edit Order of feeds</span><span class="sm-view">Edit Order</span></a></li>
                <li><a href="/munches#emailModal">Email Preferences</a></li>
              </ul>
            </div>
```

**Comment by picturepan2** [comment]
@Jped `button` can NOT be focused even with tabindex. Use `a` instead.

**Comment by Jped** [comment]
@picturepan2 Thanks for a quick response! That fixes the issue, but now the dropdown doesnt close, is there a way to get it close when hitting the link again?

**Comment by roemhildtg** [comment]
Clicking the link again won't change the focused state of the link (which controls the visibility). You'd probably have to do a little javascript to get a truly toggle-able dropdown.

**Comment by picturepan2** [comment]
@Jped Javascript is better with the component. But you can add a clickable mask element to focus another target, as Spectre Docs does it with the mask below to close the sidebar in the mobile. 

<a href="#sidebar-close" id="sidebar-close" class="docs-nav-clear"></a>

**Comment by EzzDev** [comment]
@picturepan2 Same issue here i am using a tag still not working

even in documentation the dropdown button not working too check it with Safari on IOS

https://picturepan2.github.io/spectre/components.html#menus

**Comment by jloh** [comment]
I'm running into this now as well. When clicking off a dropdown in iOS the dropdown doesn't disappear.

**Comment by natxocc** [comment]
Me too. IOS 10.3. Dropdown doesn't disappear clicking outside dropdown.
