### ISSUE TITLE
Worrying about namespaces

### ISSUE THREAD

**Issue by iredmail** [picturepan2/spectre#267]
Many classes use short prefix like `c-`, `d-`, it's not easy to understand what `c`, `d` mean, also with more tools introduced in future release, will give users more confusion.

For Cursors:

* `c`-hand (`cursor-hand` is better)
* `c`-move
* `c`-zoom-in
* `c`-zoom-out
* `c`-not-allowed
* `c`-auto

Display utilities:

* `d`-block (`display-block` is better)
* `d`-inline
* `d`-inline-block

**Comment by picturepan2** [comment]
@iredmail `c-` means `cursor` and `d-` means `display`.
