### ISSUE TITLE
Date field: dd/mm/yyyy?

### ISSUE THREAD

**Issue by LucasPadovan** [picturepan2/spectre#269]
Hello!
I've been trying to find a way to change the order of the days and the months that is by default on the calendar to use dd/mm/yyyy. Is there a way to configure this?
Actually, being able to translate the datepicker will be great also.

Thanks!

**Comment by picturepan2** [comment]
@LucasPadovan It depends on user browser's settings and language preferences.

**Comment by LucasPadovan** [comment]
:+1: thanks! working fine after switching browser's settings
