### ISSUE TITLE
Font size look so small

### ISSUE THREAD

**Issue by iamchetanp** [picturepan2/spectre#271]
Hello Some fonts size looks really small. For Ex. in Navbar, Button, Popup close icon etc.

**Comment by picturepan2** [comment]
@iamchetanp What sizes do you prefer?

**Comment by iamchetanp** [comment]
16px is body font

**Comment by victorparmar** [comment]
I can second this issue, the default setup is too small for our uses. I have made a custom spectre build with the following `$html-font-size: 23px !default;` but it would be nice to have a slightly larger default.

**Comment by picturepan2** [comment]
@iamchetanp Spectre default font size is 16px (.8rem) in v0.4.4.

**Comment by Geczy** [comment]
Good change !

**Comment by picturepan2** [comment]
@Geczy Please tell me if anything is not good with the new font size.
