### ISSUE TITLE
SASS default variables

### ISSUE THREAD

**Issue by elias-garcia** [picturepan2/spectre#273]
Hi! I'm working with the SASS version of the project and I miss a lot the `!default` keyword in order to overwrite the default framework variables using another file like Bootstrap. I'm not an expert in SASS so I don't know if there is another way of doing this currently.

Keep the good work and thanks!

**Comment by picturepan2** [comment]
@elias-garcia I have `!default` flags in the v0.4.1 version. Coming soon.
