### ISSUE TITLE
Add column ordering

### ISSUE THREAD

**Issue by linuxdoesrock** [picturepan2/spectre#274]
First of all, thanks for your awesome work @picturepan2! I enjoy your work a lot. I'm trying to change the column order as in https://codepen.io/anon/pen/BdeBxG 
I want that on a mobile device the column are stacked as:
1
2
3
4
Bootstrap provides  .col-md-push-* and .col-md-pull-* modifier classes. Is there something similar planed?

**Comment by picturepan2** [comment]
@linuxdoesrock flex order is not planned. But there is grid offset https://picturepan2.github.io/spectre/layout.html#grid .
