### ISSUE TITLE
Sidebar does not close properly in IE11

### ISSUE THREAD

**Issue by Potentiator** [picturepan2/spectre#275]
First, I just want to say great work! This framework looks pretty awesome, and will be using for a project soon.

Second, I found an issue with the sidebar menu items not closing properly in IE11 when the window is resized (for the docs page). It works fine in Chrome and MS Edge. The accordion component is a little flaky in IE11 as well with the visibility of the menu items when expanded. 

Will you be releasing this as a component (Sidebar)? I could proabably extract what I need, but it would be great to have this as a standalone (perhaps with Icons).

Thanks!

**Comment by picturepan2** [comment]
@Potentiator What I use in the sidebar is the [Accordions component](https://picturepan2.github.io/spectre/components.html#accordions). I will test it in IE11 and see what bug it is. Thank you.

**Comment by Potentiator** [comment]
@picturepan2 Great - thanks!

Yes, releasing the off-screen sidebar as a component would be useful. I can probably figure it out from the docs, so not a big issue for me.

**Comment by picturepan2** [comment]
@Potentiator The bug in IE11 is fixed in v0.4.1 which is still in dev.

**Comment by Potentiator** [comment]
@picturepan2 Thanks!

**Comment by picturepan2** [comment]
@Potentiator Released https://picturepan2.github.io/spectre/elements.html#media

**Comment by Potentiator** [comment]
@picturepan2 Awesome - appreciate the quick turnaround on this one.

**Comment by picturepan2** [comment]
@Potentiator Off-canvas is here https://picturepan2.github.io/spectre/experimentals.html#off-canvas
