### ISSUE TITLE
problem :global in .form-input-hint sass

### ISSUE THREAD

**Issue by jagcompacion** [picturepan2/spectre#279]
First of all, this is probably the cleanest framework i've used so far. the bug that i got is when i'm using the spectre sass and i want to put it :global, the result in css is not the same. 
I did try:
```javascript
:global {
   @import 'spectre/spectre';
}
 ```
instead of:
```javascript
:global .has-success .form-input-hint { /**/ }
 ```
it generates:
```javascript
.has-success :global .form-input-hint { /**/ }
 ```

Hope you can help me on this...

**Comment by picturepan2** [comment]
@jagcompacion 
```
.form-input,
.form-select {
  .has-success &,
  &.is-success {
    ...
  }
}
```
`:global` is added after `.has-success`.

**Comment by picturepan2** [comment]
@jagcompacion May I know why do you need `:global`?

**Comment by jagcompacion** [comment]
i'm using [react-css-module](https://github.com/gajus/react-css-modules) (from [css-modules](https://github.com/css-modules/css-modules) concept) which isolate custom style on a certain component but i want also to have a css framework of all the component. The purpose of this is to make it more [atomic design](http://bradfrost.com/blog/post/atomic-web-design/) but still using the css framework as the base. The guide told me to add :global on the css framework but it needs to be on sass to make it easier and when i add it, it generates same thing on the top.

**Comment by picturepan2** [comment]
@jagcompacion You can wrap `:global` outside the output CSS.
