### ISSUE TITLE
Video 标签的用例？

### ISSUE THREAD

**Issue by dimlau** [picturepan2/spectre#280]
本来以为是没考虑 `<video>` 标签，但是看了一下 css 好像单独对 `.video-responsive video` 进行了区别定义。

那么这种：

```
<div class="video-responsive">
<video controls="controls" src="https://images.apple.com/media/cn/airpods/2016/94916564_4bfa_4362_8b6c_b5c8fc822e3d/films/feature/airpods-feature-tft-cn-20160907_1536x640h.mp4">你的浏览器暂不支持播放该视频</video>
 </div>
```

怎么避免视频之前的 56.25% 的空白？推荐的 video 标签用例应该是怎么样的？

.

**Comment by picturepan2** [comment]
原本是 `<video class="video-responsive" ...>...</video>`，看起来还有些不严谨，我修复一下。

**Comment by dimlau** [comment]
我先 `margin-top: -56.25%` 了……

**Comment by picturepan2** [comment]
Updated https://picturepan2.github.io/spectre/elements.html#media
