### ISSUE TITLE
tab-block issue 

### ISSUE THREAD

**Issue by anthrogan** [picturepan2/spectre#281]
Love the pack buddy, great work

This isn't really an issue with spectre, I'm not really sure if its a bug with prefixer or IE11 tbh... It's more likley to be IE11 as 1 0 0 works fine in other places.

Issue (after autoprefixer):
```
.tab.tab-block .tab-item {
  -ms-flex: 1 0 0;
  flex: 1 0 0;
  text-align: center;
}
```

fix:
```
.tab.tab-block .tab-item {
  -ms-flex: 1 0 auto;
  flex: 1 0 0;
  text-align: center;
}
```

Refernce for the

**Comment by picturepan2** [comment]
@anthrogan I think it is a bug of IE 11 https://connect.microsoft.com/IE/feedback/details/949764/ie-11-incorrectly-rejects-flexbox-shorthand-syntax-flex-1-1-0-as-invalid

**Comment by anthrogan** [comment]
I thought as much!
