### ISSUE TITLE
How to increase icon size?

### ISSUE THREAD

**Issue by iredmail** [picturepan2/spectre#284]
Dear developers,

How can i increase the icon size? This is not mentioned in document.

**Comment by picturepan2** [comment]
@iredmail You can use `font-size` to control icon sizes. 
```
.icon {
   font-size: 1rem;
}
```

**Comment by iredmail** [comment]
Not this way. I was talking about size control like fontawesome, check examples here: http://fontawesome.io/examples/

I expect something like this:

* Normal size:
```
<i class="icon icon-menu"></i>
```

* 2 times large, 3 times large:
```
<i class="icon icon-menu icon-2x"></i>
<i class="icon icon-menu icon-3x"></i>
```

**Comment by kapolos** [comment]
@iredmail 

`.fa-4x` is simply `font-size: 4em;`, you can roll your own class names like that.

**Comment by iredmail** [comment]
Since this feature is so basic and used frequently, i hope developers can help review my pull request and merge it. Thank you.
https://github.com/picturepan2/spectre/pull/285

**Comment by picturepan2** [comment]
@iredmail Added Icon sizes in v0.4.3 https://github.com/picturepan2/spectre/releases/tag/v0.4.3
