### ISSUE TITLE
Error while loading elements 

### ISSUE THREAD

**Issue by iojanis** [picturepan2/spectre#286]
See yourself 

http://imgur.com/a/hFbW

**Comment by picturepan2** [comment]
@iojanis The image is down.

**Comment by iojanis** [comment]
My bad... 

https://imgur.com/a/hFbWS

**Comment by picturepan2** [comment]
@iojanis What browser and OS?

**Comment by iojanis** [comment]
That's Safari 10 on iOS 10.3

**Comment by lenovouser** [comment]
Weird, I don't get this on **iOS** `v10.3.3 (14G60)` with Safari 10:

![spectre.css on Safari 10 / iOS v10.3](https://i.lenovouser.me/2Kra9rbH.PNG)

**Comment by iojanis** [comment]
It's only with elements from the components page. The glitch appears every time I revisit the page.

**Comment by lenovouser** [comment]
Hmmm. Thats really weird. I scrolled through the whole documentation and while it happens less to me than to you I also found some spots:

![](https://i.lenovouser.me/vyUtK2F1.PNG)

It seems to be the `display: flex` property on `.columns`, when I disable that it goes back to normal.

![](https://i.lenovouser.me/U9jL8bm5.png)

**Comment by picturepan2** [comment]
@iojanis @lenovouser Any more details?
Actually I have no idea what bug it is.

**Comment by lenovouser** [comment]
@picturepan2 well, it seems to be `display: flex` on `.columns` - but I have no idea why. Apple already displays a ⚠️ in the Developer Tools, and when I delete the property the glitch disappears.

**Comment by picturepan2** [comment]
@iojanis @lenovouser Fixed in v0.4.2. It seems a `details/summary` bug in Safari.

**Comment by picturepan2** [comment]
@all Fixed in v0.4.2 and it is merged. https://picturepan2.github.io/spectre/
