### ISSUE TITLE
Please add version number in *.min.css

### ISSUE THREAD

**Issue by iredmail** [picturepan2/spectre#289]
Please add version number in *.min.css, it will help understand which version we're using.

**Comment by picturepan2** [comment]
@iredmail This makes upgrading, both updating manually or using package managers, messy. 
Why do you think this change is necessary?

**Comment by victorparmar** [comment]
If you want we can have a dist version with the version number and one without. I personally feel that it would not be too much work to change the version number on upgrade (the `package.json` file needs to be changed anyways).

**Comment by picturepan2** [comment]
@victorparmar Version number is added in v0.4.4.
