### ISSUE TITLE
(feature)Full screen modal 

### ISSUE THREAD

**Issue by kwstaskara** [picturepan2/spectre#293]
I love this framework and one feature i miss so much,  is a full screen modal, it would be a nice to have an option like this. Many apps make use of it for many reasons such as reading,about pages, terms of use,user profiles etc.

**Comment by picturepan2** [comment]
@kwstaskara Do you mean full screen content container? Can you show me some examples?

**Comment by kwstaskara** [comment]
Something like this https://codepen.io/vajkri/pen/OPYqav
Or this http://joaopereirawd.github.io/animatedModal.js/

**Comment by picturepan2** [comment]
@kwstaskara Added large Modals in v0.4.3 https://github.com/picturepan2/spectre/releases/tag/v0.4.3

**Comment by kwstaskara** [comment]
Thank you works nice.
One note, full screen modal content should be positioned at the top of it or almost at the top and when you scroll down the modal you also scroll down the body page which is a problem.
Anyway i added some custom css and now modal body is not scrolling down body page.

**Comment by picturepan2** [comment]
@kwstaskara You need to add `overflow: hidden;` to `body`. Do you have pure CSS solution?

**Comment by kwstaskara** [comment]
the only way with a pure css solution would be with modified checkbox.so opening a modal with checkbox lets you use the checked: pseudoclass. But in my opinion not worth.
