### ISSUE TITLE
Can't use custom IDs or Tags for Filter Feature

### ISSUE THREAD

**Issue by kevinfiol** [picturepan2/spectre#294]
Please see this CodePen displaying the issue: https://codepen.io/anon/pen/KXWLQa?editors=1000
The top filter will work, but the bottom will not.

I was banging my head trying to figure out why my filters were not working. It seems as long as the user ONLY uses the filter IDs described on the site ('tag-all', 'tag-action', 'tag-roleplaying', 'tag-shooter', etc) it will work, but otherwise, this feature is useless.

**Comment by picturepan2** [comment]
@kevinfiol In newly released v0.4.3, Filters use `tag-1` to `tag-8` to flag different tags. `tag-0` is reserved for clearing filter (showing all). You can overwrite `$filter-number` in `_filters.scss` to have more filters. https://picturepan2.github.io/spectre/experimentals.html#filters
