### ISSUE TITLE
How to do responsive layout with window width bigger than 1280px

### ISSUE THREAD

**Issue by zwz** [picturepan2/spectre#295]
I want a responsive toast.
So here is the main code:
```
<div class="toast-container columns">
  <div class="column col-mx-auto col-xs-12 col-sm-9 col-md-6 col-lg-4 col-xl-3">
    <div class="toast toast-error">
       msg
    </div>
  </div>
</div>
```
The toast responds well when resize the window, except when the window width exceeds 1280px, the toast is 100% width. 
I know I can set max-width. But I'd like to know what's recommended way to this issue.

**Comment by picturepan2** [comment]
@zwz Use `col-x` classes when it is wider than 1280px.

**Comment by zwz** [comment]
OMG, I just forgot it. Thanks.
