### ISSUE TITLE
Suggestion: list-position-style

### ISSUE THREAD

**Issue by dacodekid** [picturepan2/spectre#296]
The `inside` value on [list elements](https://github.com/picturepan2/spectre/blob/master/src/_typography.scss#L106-L120) causing couple issues.

1. It moves text to the left most margin
![image](https://user-images.githubusercontent.com/10047844/31017126-7dc8395c-a4f5-11e7-8c96-e826aa347639.png)

2. If there is a paragraph element inside the list, it pushes them down to next line
![image](https://user-images.githubusercontent.com/10047844/31017170-a60691f2-a4f5-11e7-9204-96f246950f1f.png)

Would appreciate if you could leave that value to its default (`outside`) and use padding instead.  This is what I did to overcome the above.
```css
ol,
ul {
    padding-left: 2rem;
    list-style-position: outside;
}
```

**Comment by picturepan2** [comment]
@dacodekid I don't plan to add it. Thank you anyway.

**Comment by zwz** [comment]
@picturepan2 
IMO the suggestion by @derek73 should be adopted if this modification would not affect any other aspects of spectre.css.  

I just came across the same issue @dacodekid when I have
```
<ul><li><p>blah blah</p></li></ul>

<ol><li><p>blah blah</p></li></ol>
``` 

Removing the `inside`, the text of the content could be kept on the same line of the bullet/number.
