### ISSUE TITLE
Encode empty spaces in css url for select field background icon

### ISSUE THREAD

**Issue by mariodev** [picturepan2/spectre#297]
First of all.. congrats on a great css framework :) I've started using bits of it in all of my current projects.

Since I'm not using the dist version, but rather including some parts of it, I came into one issue.
When including select field icon and going through compress process, the url part gets minimised and therefore becomes invalid and icon is not displayed:

```
background: #fff url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 5'%3E%3Cpath fill='%23667189' d='M2 0L0 2h4zm0 5L0 3h4z'/%3E%3C/svg%3E") no-repeat right .35rem center/.4rem .5rem;
```

I figured this could be fixed simply by replacing empty spaces with encoded version `%20` which I think is generally a good practice when dealing with url string.

**Comment by picturepan2** [comment]
@mariodev Fixed in v0.4.3 https://github.com/picturepan2/spectre/releases/tag/v0.4.3 . Thank you.
