### ISSUE TITLE
Problem in responsive mode using table and panel

### ISSUE THREAD

**Issue by Kcchouette** [picturepan2/spectre#303]
Hello.

At first, thank you very much for spectre.css

I have a problem when using panel and table in a same class columns, here is my code: https://jsfiddle.net/2cwna3vh/

If I am on PC, it's ok: 
![screenshot-2017-10-3 screenshot](https://user-images.githubusercontent.com/3000936/31127935-8d00200c-a850-11e7-92ea-0f1251f78d69.png)

But on smartphone, here is the result! 
![screenshot-2017-10-3 screenshot 2](https://user-images.githubusercontent.com/3000936/31127964-98a68c02-a850-11e7-811a-721464c65fd9.png)

Does I use correctly the component (and is it a bug) or not?

Thank you.

**Comment by picturepan2** [comment]
@Kcchouette Checking this issue.

**Comment by picturepan2** [comment]
@Kcchouette 
```
<div class="columns">
  <div class="column col-2 col-sm-12">
    <div class="panel">...</div>
  </div>
  <div class="column col-10 col-sm-12 col-ml-auto">
    <table class="table">...</table>
  </div>
</div>
```

**Comment by Kcchouette** [comment]
Indeed, using `col-sm-12` fix my problem. Thank you for the help @picturepan2
