### ISSUE TITLE
iphone 滑动很卡，怎么办？

### ISSUE THREAD

**Issue by Damingboss** [picturepan2/spectre#305]
<!doctype html>
<html class="no-js">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="description" content="">
		<meta name="keywords" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>滑动很慢</title>
		<link rel="stylesheet" href="css/spectre.min.css" />
		<link rel="stylesheet" href="css/spectre-exp.min.css" />
		<link rel="stylesheet" href="css/spectre-icons.min.css" />
		<link rel="stylesheet" href="css/public.css" />
		<link rel="alternate icon" href="img/logo.jpg">
		<link rel="apple-touch-icon-precomposed" href="img/logo.jpg">
	</head>

	<body>
		<div class="off-canvas">
			<input type="checkbox" class="off-canvas-checkbox" id="sidebar-checkbox" name="sidebar-checkbox" hidden="">
			<label class="off-canvas-toggle btn btn-primary btn-lg" for="sidebar-checkbox">
                  <i class="icon icon-menu"></i>
                </label>
			<div class="off-canvas-sidebar flex-centered">
				<span>Sidebar</span>
			</div>
			<div class="off-canvas-content">
				<div id="cards" class="container">
					<h3 class="s-title"><a href="#cards" class="anchor" aria-hidden="true">#</a>Cards</h3>
					<div class="docs-note">
						<p>Cards are flexible content containers.</p>
					</div>
					<div class="columns">
						<div class="column col-6 col-xs-12">
							<div class="card">
								<div class="card-image">
									<img class="img-responsive" src="img/osx-el-capitan.jpg" alt="OS X El Capitan">
								</div>
								<div class="card-header">
									<div class="card-title h5">Microsoft</div>
									<div class="card-subtitle text-gray">Software and hardware</div>
								</div>
								<div class="card-body">
									Empower every person and every organization on the planet to achieve more.
								</div>
								<div class="card-footer">
									<a href="#cards" class="btn btn-primary">Do</a>
								</div>
							</div>
						</div>
						<div class="column col-6 col-xs-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title h5">Apple</div>
									<div class="card-subtitle text-gray">Hardware and software</div>
								</div>
								<div class="card-image">
									<img class="img-responsive" src="img/osx-yosemite.jpg" alt="OS X Yosemite">
								</div>
								<div class="card-body">
									To make a contribution to the world by making tools for the mind that advance humankind.
								</div>
								<div class="card-footer">
									<div class="btn-group btn-group-block">
										<button class="btn btn-primary">Buy</button>
										<button class="btn">Buy</button>
										<button class="btn">Buy</button>
									</div>
								</div>
							</div>
						</div>
						<div class="column col-6 col-xs-12">
							<div class="card">
								<div class="card-image">
									<img class="img-responsive" src="img/macos-sierra-2.jpg" alt="macOS Sierra">
								</div>
								<div class="card-header">
									<button class="btn btn-primary float-right"><i class="icon icon-plus"></i></button>
									<div class="card-title h5">Google I/O</div>
									<div class="card-subtitle text-gray">Software and hardware</div>
								</div>
								<div class="card-body">
									An immersive, three-day experience focused on exploring the next generation of technology, mobile and beyond.
								</div>
							</div>
						</div>
						<div class="column col-6 col-xs-12">
							<div class="card">
								<div class="card-image">
									<img class="img-responsive" src="img/osx-el-capitan-2.jpg" alt="OS X El Capitan">
								</div>
								<div class="card-footer">
									<a href="#cards" class="btn btn-primary">Buy</a>
									<a href="#cards" class="btn btn-link">Share</a>
								</div>
								<div class="card-body">
									<strong>Surface Studio</strong>. Turn your desk into a Studio. Surface Studio is designed for the creative process.
								</div>
							</div>
						</div>
						<div class="column col-6 col-xs-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title h5">Apple</div>
									<div class="card-subtitle text-gray">Hardware and software</div>
								</div>
								<div class="card-body">
									To make a contribution to the world by making tools for the mind that advance humankind.
								</div>
								<div class="card-image">
									<img class="img-responsive" src="img/macos-sierra.jpg" alt="macOS Sierra">
								</div>
							</div>
						</div>
						<div class="column col-6 col-xs-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title h5">Google</div>
									<div class="card-subtitle text-gray">Software and hardware</div>
								</div>
								<div class="card-body">
									Organize the world’s information and make it universally accessible and useful.
								</div>
								<div class="card-image">
									<img class="img-responsive" src="img/osx-yosemite-2.jpg" alt="OS X Yosemite">
								</div>
								<div class="card-footer">
									<a href="#cards" class="btn btn-primary">Search</a>
									<a href="#cards" class="btn btn-link">Share</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>

</html>

**Comment by Damingboss** [comment]
<div class="off-canvas-content" style="-webkit-overflow-scrolling : touch;">
这里加上这个可以了

**Comment by picturepan2** [comment]
@Damingboss 加上什么？

**Comment by Damingboss** [comment]
加上可以，这个组件不行，有时候会滑动底板，上边内容不滑动。

**Comment by Damingboss** [comment]
iphonezb.cn/mall/index.html
产品页，双击空白底板。滑动就是底板了。再滑上面内容就不行了

**Comment by Damingboss** [comment]
还有那个 go to top 为什么不可以。#top跳转也不行

**Comment by picturepan2** [comment]
@Damingboss 我这里正常的，你那里是什么浏览器？版本号？

**Comment by Damingboss** [comment]
电脑都是很正常的，微信里面不行，移动端不行的

**Comment by picturepan2** [comment]
@Damingboss ……那请问一下您：
移动端是什么平台？什么浏览器？什么版本号？

**Comment by Damingboss** [comment]
好了，没有用Off-canvas。
off-canvas：iphonezb.cn/mall/old/index.html,
用了columns做了，
背景色可以加个 bg-white。

**Comment by picturepan2** [comment]
@Damingboss 好的。

**Comment by Damingboss** [comment]
现在移动端优先，可以考虑多一些移动端的内容。这样商用上手快一些。九宫格，图片浏览模式，底部导航菜单。最好是能有几个案例。谢谢作者能及时看到留言
