### ISSUE TITLE
docs.scss output is different than provided docs.css

### ISSUE THREAD

**Issue by krlklm** [picturepan2/spectre#306]
When i compile /spectre.css/docs/src/docs.scss i get a different a output than the provided docs.css in /spectre.css/docs/css/docs.css

For example the docs.scss outputs this in line 6:

/* Spectre New Docs */
.s-container > .columns {
  flex-flow: nowrap;
  min-height: 100vh; }

While the provided docs.css looks like this:
/* Spectre New Docs */
.s-container > .columns {
  -ms-flex-flow: nowrap;
  flex-flow: nowrap;
  min-height: 100vh;
}

So the line with "-ms-flex-flow: nowrap;" is missing. (Just as an example - there is more missing..)

(Version 0.4.3)

**Comment by picturepan2** [comment]
@krlklm I guess it is because the Autoprefixer's browser usage database. You can update the NPM packages and re-compile the SASS files. 

And please check the rules in `package.json`:
```
"browserslist": [
    "last 4 Chrome versions",
    "Edge >= 12",
    "Firefox ESR",
    "last 4 Safari versions",
    "last 4 Opera versions",
    "Explorer >= 10"
  ]
```

**Comment by krlklm** [comment]
Didn't know about this. Still learning. Thanks!

**Comment by picturepan2** [comment]
@krlklm The package `caniuse-lite` stores browser's usage and CSS feature support info based on caniuse.com data.
