### ISSUE TITLE
Close sidebar in a single page application

### ISSUE THREAD

**Issue by roboriaan** [picturepan2/spectre#308]
Is it possible to close the sidebar programmatically? I've tried adding #sidebar-close to one of the links in the side menu but it stays open. Now it's possible that it doesn't work because of hashbang routing that I use in my SPA. Only when I select the address bar and hit enter does it close.

**Comment by picturepan2** [comment]
@roboriaan Yes, I will add that in v0.4.5 this week.

**Comment by roboriaan** [comment]
Thanks for this fantastic framework btw!

**Comment by picturepan2** [comment]
@roboriaan You can use the class `active` to open the off-canvas sidebar or remove the class to close it. https://github.com/picturepan2/spectre/releases/tag/v0.4.5
