### ISSUE TITLE
Customizing fonts recommended

### ISSUE THREAD

**Issue by rgeronimi** [picturepan2/spectre#309]
Hello, the documentation is not explicit as to whether customizing fonts (e.g., to use a specific serif font that we declare with @font-face separately) is recommended, i.e. not only possible but roughly compatible with the CSS layout technics of the library, or not.

This is of course possible technically to customize it thanks to the build process, but should we expect reasonably good layout results out of it?

**Comment by picturepan2** [comment]
@rgeronimi Customizing fonts works fine. I don't think there will be big problem.

**Comment by rgeronimi** [comment]
Thanks, will try

**Comment by picturepan2** [comment]
@rgeronimi The font family defined in Spectre is one of the best practice ones which work best on all popular browsers and platforms. You can always change it to match your need.
