### ISSUE TITLE
Columns margins

### ISSUE THREAD

**Issue by mgohin** [picturepan2/spectre#31]
.columns {
        display: -webkit-box;
        display: flex;
        display: -ms-flexbox;
        display: -webkit-flex;
        -ms-flex-wrap: wrap;
        -webkit-flex-wrap: wrap;
        flex-wrap: wrap;
        margin-left: -1rem;
        margin-right: -1rem;
    }

Shouldn't it be `.column .columns` for those negative margins ? 

Negative margins got me an undesired horizontal scroll :/

**Comment by picturepan2** [comment]
Sorry, I updated [the doc](http://picturepan2.github.io/spectre/#layout). You can add a container with the class `container` outside the `columns`. It should solve your problem. 😄

**Comment by mgohin** [comment]
I must add a new div around all my div.columns, is my suggestion not better ?

**Comment by picturepan2** [comment]
Negative margin solution is one of the `best practices`. In this way, column widths can be divided equally without complex css code.
