### ISSUE TITLE
Since v0.4.3, doesn't work with create-react-app

### ISSUE THREAD

**Issue by Tcheny** [picturepan2/spectre#310]
Spectre doesn't work with bundle create-react-app v1.4.0, I have to install spectre.css v0.4.2 to make it work.

**Comment by roemhildtg** [comment]
You might need to install the sass-loader. Have you tried this? https://github.com/webpack-contrib/sass-loader

**Comment by roemhildtg** [comment]
I just switched my import from 
`import 'spectre.css';`

to 
`import 'spectre.css/dist/spectre.min.css`;

and it is working, rather than installing a sass loader.

**Comment by picturepan2** [comment]
@roemhildtg Should I update the `package.json` for better import support?

**Comment by roemhildtg** [comment]
I think it makes sense to point your main to the distributable css file, yes. Others do this as well: https://github.com/chinchang/hint.css/blob/master/package.json#L7

**Comment by viiiprock** [comment]
I use 4.4 and import right away in `index.js`
it works well with styled-components too

**Comment by Tcheny** [comment]
Ok! Thanks for your help!
