### ISSUE TITLE
Carousels do not work well with each other.

### ISSUE THREAD

**Issue by yahtnif** [picturepan2/spectre#311]
When using carousel more than one, they do not display well.

 [demo on jsfiddle](https://jsfiddle.net/km1ryjwa/1/)

**Comment by tomcam** [comment]
I'm sorry if this sounds rude, but why would you want to have 2 carousels on the same page? This seems like a nightmare for both the user (too many foci of attention) and for accessibility.

**Comment by picturepan2** [comment]
@yahtnif Thank you. I am looking into it.
@tomcam For example, the carousel sliders for two or more products in one post.

**Comment by picturepan2** [comment]
@yahtnif Spectre supports multiple carousels in one page. Make sure using different `name` for inputs for different carousels.

**Comment by yahtnif** [comment]
@picturepan2 Thanks
