### ISSUE TITLE
Rename Labels to badges

### ISSUE THREAD

**Issue by m5o** [picturepan2/spectre#316]
In Bootstrap v4, labels and badges got renamed; see the [migration guide](https://getbootstrap.com/docs/4.0/migration/#labels-and-badges)

> Renamed `.label` to `.badge` to disambiguate from the `<label>` element.

I would volunteer to submit a pull request if this feature parity is desired. 
What do you think?

---

📝 **Doc References**
* https://getbootstrap.com/docs/4.0/components/badge/#contextual-variations
* https://picturepan2.github.io/spectre/elements.html#labels

**Comment by picturepan2** [comment]
@m5o I am not planning the renaming. Good idea but it still needs some considerations.

**Comment by picturepan2** [comment]
@m5o Badges in Spectre are floated labels with number in them. And it has some unique usage with other components. I don't think merging labels and badges are good. What do you think?

**Comment by m5o** [comment]
Yes, you‘re right. I did not consider this fact.
