### ISSUE TITLE
When to use rem when to use em

### ISSUE THREAD

**Issue by tomcam** [picturepan2/spectre#317]
I think originally spectre.css was meant to be em-based but it seems to be mostly rem-based now. When should I use rem and when should I use em?

**Comment by picturepan2** [comment]
@tomcam Recommend this article on the difference between `rem` and `em`. `rem` is based on root/html font-size, while `em` is based on the parent font-size. It depends on how you calc your sizes.

**Comment by tomcam** [comment]
Thank you. I think I was just being a bit too literal-minded and expected it to be all or nothing.

**Comment by picturepan2** [comment]
@tomcam No problem. For example, in pure CSS icons, I use `em` unit to make the icons easier to change the sizes by changing the parent font-size.
