### ISSUE TITLE
icon-edit图标个人感觉没有对齐~不知道作者会不会调整一下

### ISSUE THREAD

**Issue by ydq** [picturepan2/spectre#319]
如题，如下图：
<img width="237" alt="icon-edit" src="https://user-images.githubusercontent.com/8097340/32087644-e5b0a218-bb0f-11e7-8a5b-f17d3d306673.png">
<img width="237" alt="icon-edit" src="https://user-images.githubusercontent.com/8097340/32087753-9c168c7a-bb10-11e7-9f5a-495835c96e19.png">
希望作者能微调一下拯救一下我这样的强迫症患者~谢谢啦

**Comment by picturepan2** [comment]
@ydq 打算把图标拆分出去，到时候会修复一些问题，对齐应该会解决。

**Comment by ydq** [comment]
@picturepan2 感谢您的作品，并已经在部分项目中正式使用啦~~
同时在自己博客上转推了一下 http://darren.ink/archives/150
