### ISSUE TITLE
Form controls size

### ISSUE THREAD

**Issue by victorwpbastos** [picturepan2/spectre#32]
Would be great if form controls (inputs, selects, switches and input groups) could have size classes like buttons has.

**Comment by picturepan2** [comment]
@victorwpbastos Inputs and Selects have smaller size by adding `input-sm` and `select-sm`.

**Comment by picturepan2** [comment]
I updated [the doc here](http://picturepan2.github.io/spectre/).

**Comment by victorwpbastos** [comment]
Yes, larger sizes for selects, inputs, switches and input groups would be great. Thanks for the attention and congratulations for the great job!

**Comment by picturepan2** [comment]
Spectre.css now provides small/large input, select and input groups. But no small or large switches.https://picturepan2.github.io/spectre/#forms
