### ISSUE TITLE
Use `Source Han Sans` Prior to/Instead of `Microsoft Yahei`

### ISSUE THREAD

**Issue by ryh** [picturepan2/spectre#321]
Use `Source Han Sans`Prior to/Instead of `Microsoft Yahei`
请用`思源黑体` 优先于/替换 `微软雅黑`

虽然方正莫名其妙的干涉font-family 但有更好的选择的[思源黑体](https://github.com/adobe-fonts/source-han-sans)不是更好么
https://github.com/picturepan2/spectre/blob/master/src/_variables.scss#L43
REF1: https://www.v2ex.com/t/398027 被方正警告网页不许使用微软雅黑字体了
REF2:https://zhuanlan.zhihu.com/p/30568782 对不起，微软雅黑不是免费字体

**Comment by picturepan2** [comment]
@ryh 微软雅黑用在 CSS Font-family 没有法律问题，并没有存储分发雅黑字体文件。
