### ISSUE TITLE
Adding a custom scss in the root did not get compiled to /dist

### ISSUE THREAD

**Issue by yoneth** [picturepan2/spectre#327]
I followed the instruction here https://picturepan2.github.io/spectre/getting-started.html#importing

I create _custom_style.scss_ in the root folder. I wrote some random css syntax, then build using gulp. Unfortunately it did not compiled into _/dist/spectre.css_ file. 

Is there something I missed?

**Comment by picturepan2** [comment]
@yoneth This instruction is for importing Spectre to your own project. Did you import Sass to your own project folder?

**Comment by yoneth** [comment]
No I did not. How do I do that?
Thanks for your response.

**Comment by picturepan2** [comment]
@yoneth If you already have a project, you can import Spectre in this way. If not, you can just fork the Spectre.css to custom your version.
