### ISSUE TITLE
Flexbox grid question

### ISSUE THREAD

**Issue by cnbattle** [picturepan2/spectre#329]
in andriod phone. only chrome and firefox browser,the pages  right number is show。other browser is not show.
my test website: bbs.cnbattle.com.

I am not a front-end programmer, i am phper. 0.0

**Comment by cnbattle** [comment]
firefox  browser: http://ww2.sinaimg.cn/large/0060lm7Tly1fl8q1w2xs1j30k00zkgqr.jpg 
UC browser: http://ww1.sinaimg.cn/large/0060lm7Tly1fl8q1vzpibj30k00zktd3.jpg

**Comment by picturepan2** [comment]
@cnbattle Sorry for the late reply. It might be a `Flexbox` support issue. What is the version of UC browser you use?

**Comment by cnbattle** [comment]
thanks you reply.brfore i set there blackground-color:#00336699;color:#ffffff;but other browsers donot use #00336699;so there not show. I rectification now
