### ISSUE TITLE
Spacing between grid rows

### ISSUE THREAD

**Issue by benjamin-bergia** [picturepan2/spectre#330]
For some reason when I copy the layout doc and use the latest version from the CDN, 
I don't get any space between rows.

https://jsfiddle.net/qn0w6och

Am I missing anything?

**Comment by anthrogan** [comment]
The CSS in documents uses the 'docs' (spectre.css/docs/css/docs.css) it's slightly different from the dist version.

to get the desired effect adjust the css to:
`.column {`
`  -ms-flex: 1;`
`  flex: 1;`
`  max-width: 100%;`
`  padding: .4rem;`
`  /* padding-left: .4rem; */`
`  /* padding-right: .4rem; */`
`}`

**Comment by benjamin-bergia** [comment]
@anthrogan Thank you
It does work. 
Is there any way to get the same space between columns than at the left of the first column and right of the last?

I would like to have something like:
`| .4rem | column| .4rem | column | .4rem | `

**Comment by picturepan2** [comment]
@benjamin-bergia Yes, like @anthrogan said, I have added `padding: .4rem;` to `.docs-content .column`. When in the layout usage, vertical spacing is not always needed.
You can add `margin-left: 0; margin-right: 0;` to the parent `.columns`.
