### ISSUE TITLE
Getting column to collapse at <600px

### ISSUE THREAD

**Issue by tomcam** [picturepan2/spectre#331]
I have a 3 column format where I want the rightmost column to become a row at <= 600px wide. Can't figure it out. Am trying stuff like this to no avail:

```
@media (max-width: 600px) {
	.container {
		display: flex;
		flex-flow: column;
	}
}

```

The offending file is at [GitHub Source](https://github.com/tomcam/spectre-css-examples/blob/master/bold.html), [Preview](https://htmlpreview.github.com/?https://github.com/tomcam/spectre-css-examples/blob/master/bold.html)

Bonus points for anyone who can tell me why bluerobot.svg doesn't display.

**Comment by tomcam** [comment]
Remove irrelevant debug line

**Comment by picturepan2** [comment]
@tomcam 
```
<div class="columns">
   <div class="column col-4 col-sm-6"></div>
   <div class="column col-4 col-sm-6"></div>
   <div class="column col-4 col-sm-12"></div>
</div>
```

**Comment by tomcam** [comment]
Oh my goodness. Worked perfectly. Thank you.

**Comment by picturepan2** [comment]
@tomcam You're welcome.
