### ISSUE TITLE
Put icon as an input value

### ISSUE THREAD

**Issue by Kcchouette** [picturepan2/spectre#334]
Hello
Is it possible to use the spectre icon as a input value?

EG: ```<input type="submit" class="btn btn-primary" value="icon icon-arrow-right" >```

Thank you in advance

**Comment by picturepan2** [comment]
@Kcchouette Not possible with pure CSS icons. But it will work with SVG/IMG icons by setting as background.

**Comment by Kcchouette** [comment]
Can you show me example with svg pictures please?

**Comment by picturepan2** [comment]
@Kcchouette https://github.com/picturepan2/spectre/blob/721fb6f5f4d2f9e6ffdce6ec45f631ab125fdb57/src/_forms.scss#L129

**Comment by Kcchouette** [comment]
Alternative: replacing my example (````<input type="submit" class="btn btn-primary" value="icon icon-arrow-right" >````) by ````<button type="submit" class="btn btn-action" ><i class="icon icon-arrow-right"></i></button>```` does the trick
