### ISSUE TITLE
Cards - Pinterest Float Style

### ISSUE THREAD

**Issue by krlklm** [picturepan2/spectre#335]
Is it possible to have cards float (similar to Pinterest), so there are no empty spaces between vertically stacked cards (when using more than one column)?

**Comment by picturepan2** [comment]
@krlklm Yes, possible but not perfect. The order will be:
1 | 4 | 7 
2 | 5 | 8
3 | 6 | 9

While Pinterest's order is like:
1 | 2 | 3
4 | 5 | 6
7 | 8 | 9

**Comment by krlklm** [comment]
But how would i do it? At the moment it looks like [this](http://www.dienststelle.de/projekte/2017/bvgc/spectrecss_cards/cards_no.png), but i want it to look like [this](http://www.dienststelle.de/projekte/2017/bvgc/spectrecss_cards/cards_yes.png).

I'm still on Spectre CSS v0.4.4. Did it change in v0.4.5?

**Comment by picturepan2** [comment]
@krlklm Please look at this. https://codepen.io/demique/pen/BLWaXN

**Comment by krlklm** [comment]
Thanks for the link.
