### ISSUE TITLE
Breadcrumbs: breadcrumb-item

### ISSUE THREAD

**Issue by krlklm** [picturepan2/spectre#337]
In my optinion it does not look good that a breadcrumb item link is also underlined before the actual link-text when hovering or clicking. Must have something to do with this:

.breadcrumb .breadcrumb-item:not(:first-child)::before {
    color: #e7e9ed;
    content: "/";
    padding-right: .2rem;
}

**Comment by picturepan2** [comment]
@krlklm Sorry, I don't fully understand.

**Comment by krlklm** [comment]
[Here](http://www.dienststelle.de/projekte/2017/bvgc/spectrecss_cards/breadcrumb-item-hover.png) you can see, that in the Spectre CSS docs of the breadcrumbs the space in front of the breadcrumb item is underlined as well as the rest of the link:

**Comment by picturepan2** [comment]
@krlklm Ahh, I see. I will try to fix it.
