### ISSUE TITLE
Comparison sliders don't fit images responsively

### ISSUE THREAD

**Issue by paambaati** [picturepan2/spectre#338]
Images under comparison sliders (especially when the "after" image is smaller than the "before") are not fit responsively — meaning the full image isn't displayed entirely; I assume it is because of the `object-fit: none` style. `unset`ting it shows the whole image, but the sliding motion stretches the image as we slide.

@picturepan2 Is there a more elegant solution?

**Comment by picturepan2** [comment]
@paambaati If you want to compare two images like that, you will need to have same sized images. Otherwise you can not compare them.

**Comment by paambaati** [comment]
@picturepan2 Figured as much, thanks.

Do you plan to support responsive images inside comparison sliders?

**Comment by picturepan2** [comment]
@paambaati Yes. I will make use of the `img-fit-contain` and `img-responsive` classes documented [here](https://picturepan2.github.io/spectre/elements.html#media).

**Comment by picturepan2** [comment]
@paambaati The update v0.4.6 with this fix is released.

**Comment by paambaati** [comment]
@picturepan2 Thanks, but now with the `object-fit: cover` fix, the 'after' image moves with the slider, and is not perfectly superimposed over the 'original' image.

For example, see https://i.imgur.com/BJSGzps.gifv

**Comment by picturepan2** [comment]
@paambaati What is your browser and version?

**Comment by paambaati** [comment]
@picturepan2 Chrome 64.0.3269.3 on macOS.

**Comment by picturepan2** [comment]
@paambaati Does [this example](https://picturepan2.github.io/spectre/experimentals.html#comparison) work for you?

**Comment by paambaati** [comment]
@picturepan2 That example works! But I'm trying to use this particular image - https://httgp.com/content/images/2017/11/me.jpg, and it doesn't work. I've tried this image on your website too (by just modifying the page source inline), and I get the same weird dragging effect.

Does this have to do with the aspect ratio of the image?

**Comment by picturepan2** [comment]
@paambaati I don't have any issue even when I use other aspect ratio images. Can you show me your code?

**Comment by paambaati** [comment]
@picturepan2 I'm privately beta testing it. Can I DM you?

**Comment by picturepan2** [comment]
@paambaati Yes, Email is fine. picturepan2@hotmail.com.
