### ISSUE TITLE
Badges on tabs

### ISSUE THREAD

**Issue by IgnisFire** [picturepan2/spectre#34]
On tabs badges looks awful : 
![image](https://cloud.githubusercontent.com/assets/1565839/15006242/4f69fe36-11d7-11e6-87a2-d9933ee95152.png)

I know that badges on tab isn't good idea, but it will be nice if you add that feature, becouse its very beautiful way to show user new content in tab

**Comment by picturepan2** [comment]
@IgnisFire OK. I will fix it.

**Comment by IgnisFire** [comment]
thank you !

**Comment by picturepan2** [comment]
@IgnisFire Fixed in https://github.com/picturepan2/spectre/pull/35 Please pull the latest master branch. And see the examples here http://picturepan2.github.io/spectre/#tabs. Thank you.
