### ISSUE TITLE
navbar problem encountered when only one navbar-section present

### ISSUE THREAD

**Issue by cisolarix** [picturepan2/spectre#346]
When multiple navbar-sections are present, it just works pretty well.

But when only one navbar-section is provided, the content just aligns to the right.

![1511771605283](https://user-images.githubusercontent.com/1845040/33257302-b10f1f96-d390-11e7-8071-a4cad8ea9fa7.jpg)

**Comment by picturepan2** [comment]
@cisolarix Fixed in v0.5.0.
