### ISSUE TITLE
off-canvas default collapsed

### ISSUE THREAD

**Issue by natxocc** [picturepan2/spectre#347]
Is it possible to have default off-canvas collapsed independent of size of the screen?
I need to have all screen available and only acces to menu off-canvas when necessary.

PD: Great CSS!!! :-)

**Comment by picturepan2** [comment]
@natxocc It is possible. Let me think about it.

**Comment by picturepan2** [comment]
@natxocc Off-canvas updated. https://picturepan2.github.io/spectre/experimentals.html#off-canvas
