### ISSUE TITLE
Close-buttons in small modals and "x"-buttons in toasts don't work / require additional JS

### ISSUE THREAD

**Issue by boettges** [picturepan2/spectre#348]
Hello @picturepan2 
just recently got a hint to check out  Spectre and I am amazed! Great work 👌

One thing that irritated me was the inconsistency in regards to closing mechanics:

Toasts --> the "x" is a button and doesn't work / requires add. JS
Small modals --> "x" is an anker and works without JS
Small modals --> "Close" is a button and would require add. JS
Large modals --> "x" is an anker and works without JS
Large modals --> "Close" is an anker and works without JS

Just wondering, what is the reasoning behind this?

Thanks a lot in advance 😃

**Comment by picturepan2** [comment]
@boettges Thanks. Yes. For toasts, you will need JS to show or hide it. For modals, you can replace the "Close" buttons with "x" button links. I will update the examples.

**Comment by picturepan2** [comment]
@boettges [Examples updated](https://picturepan2.github.io/spectre/components.html#modals).
