### ISSUE TITLE
Text pointer glitches in input-fields, when put into the collapsable off-canvas navbar on mobile

### ISSUE THREAD

**Issue by boettges** [picturepan2/spectre#349]
Hey,
I just noticed that this error occurs on mobile Chrome and Safari on iOS, but not on their respective desktop versions.

Also the glitch only occurs when the text pointer is placed in text-input-fields, which are placed inside the collapsable vertical off-canvas navbar …
![what](https://user-images.githubusercontent.com/20265197/33428256-663b95a0-d5c8-11e7-8e45-d892a4d8a5da.gif)

… but not (still on mobile), when place inside the main content area:
![what2](https://user-images.githubusercontent.com/20265197/33428651-e83d345e-d5c9-11e7-8bb6-1e70b84a53d8.gif)

Any idea what could be causing this?

I guess that is why the off-canvas navbar is still experimental 😅

**Comment by picturepan2** [comment]
@boettges Can you show me your code?

**Comment by boettges** [comment]
I created a JSfiddle and used spectre + experimentals from a CDN and was not able to reproduce the bug on mobile, even though I iteratively applied the same style-changes, as shown above.
The issue must lay deeper and be some interference with other code of the full site.

The "bug" occurred when I tried the off-canvas sidebar for the first time, that's why I thought it was the root cause. Sorry! 🙌

**Comment by picturepan2** [comment]
@boettges No problem. Actually I am not able to reproduce the bug either. Btw, do you think how can I improve the off-canvas  component since you have used it.

**Comment by boettges** [comment]
@picturepan2 there a few things that can be improved:

- I think closing by tapping on the grayed out area on mobile is an intuitive interaction, but on desktop it took me a while to leave the side-bar at first. It would help to have a visible "x" button in addition to being able to click the whole area to close.
- The hamburger-button seems out of place, as on narrow screens it can be overlapping content. It would be nice to have its padding better interact with the padding of the main-content container.

<img width="208" alt="overlap" src="https://user-images.githubusercontent.com/20265197/33709780-c9a43eb4-db3e-11e7-9825-1541dfa42316.png">


I would also love to have more side-bar layout examples and options available and explained in the doc, such as:

1. side-bar off-canvas overlay with grayed out area
2. side-bar off-canvas push main-container over to the right 
3. side-bar toggle between expanded and icon-narrow ([example](https://demo.getgrav.org/receptar-skeleton/de)) instead of it being completely hidden. (I'm currently working on a solution, where my sidebar collapses and and leaves a 40px bar, which shows the icons used for my menu-items … it's harder to build than I thought.)
4. side-bar toggle button integrated in fixed header-bar over content area
5. side-bar toggle button mobile-input friendly in a bottom bar over content area

![overscroll](https://user-images.githubusercontent.com/20265197/33709743-a573a0a2-db3e-11e7-9a29-f08430b6b54f.jpg)

And is there a solution to color the vertical off-canvas background partially for the width of the sidebar in the sidebar color, so that during that over-scrolling rubber-band effect there isn't such a harsh color difference and cut-off that shows the by default white background?

As shown above I colored the sidebar in a dark gray everytime my scrolling reaches the top the white is really distracting. 😅

Thanks a lot!
