### ISSUE TITLE
npm version is missing btn-success class

### ISSUE THREAD

**Issue by jakubrpawlowski** [picturepan2/spectre#352]
I don't know how this happened but the [npm module](https://www.npmjs.com/package/spectre.css) despite having the same version number (0.4.7) is different than version on github.

```
.btn.btn-success {
  background: #32b643;
  border-color: #2faa3f;
  color: #fff;
```

**Comment by jakubrpawlowski** [comment]
Please disregard. Was looking at wrong version (0.4.6).

**Comment by jakubrpawlowski** [comment]
The difference in npm is only in dist folder- all files in dist are still from (0.4.6).

**Comment by picturepan2** [comment]
@jakubrpawlowski Checking.

**Comment by picturepan2** [comment]
@jakubrpawlowski my fault. it seems `dist` is still old version.

**Comment by picturepan2** [comment]
@jakubrpawlowski Fixed and published.
