### ISSUE TITLE
deprecation warning for extending a compound selector

### ISSUE THREAD

**Issue by bertmelis** [picturepan2/spectre#356]
When importing Spectre into my css via Sass, I get a deprecation warning:
```
 DEPRECATION WARNING on line 22 of <full path>/_sass/spectre/mixins/_button.scss:
Extending a compound selector, .btn-primary.loading, is deprecated and will not be supported in a future release.
See https://github.com/sass/sass/issues/1599 for details.
```
My knowledge of Sass is zero to none and my css is aged, so I'm the guy that can solve this one.

**Comment by picturepan2** [comment]
@bertmelis I think it is related to `@extend` and compound selectors. The affected code is: 
```
  &.loading {
    @extend .btn-primary.loading;
  }
```
I am looking into the issue though the Spectre code is fine.
