### ISSUE TITLE
Use smaller class names

### ISSUE THREAD

**Issue by talha-asad** [picturepan2/spectre#357]
Hey @picturepan2,

Great work, your framework looks slick. I just have one suggestion for you. Instead of `button.btn.btn-action.btn-primary.circle` why not do `button.btn.action.primary.circle`

Semantic UI uses a similar style for classes and it seems cleaner and minimal, maybe you gave this thought already and if yes, I would like to hear your thoughts

Would you be willing to support this for a future release?

I think it could save up a lot of bytes in the final css as well as the webpage itself, as it will have much shorter css classes.

**Comment by picturepan2** [comment]
@talha-asad Thanks. I think it is a coding style thing. The `btn-` or `form-` like prefixes make it clear to know what the components they are styling for. If Spectre uses simple class names, it may be conflict to other CSS styles which others are using.

**Comment by picturepan2** [comment]
@talha-asad I don't think I will move Spectre to a simpler CSS naming. What do you think?
