### ISSUE TITLE
Better colors (Themes)

### ISSUE THREAD

**Issue by AGhasemzadeh** [picturepan2/spectre#359]
Hello,
I think we can have some sets of colors or themes.

For example users like theme look like: coreui or adminlte.

**Comment by picturepan2** [comment]
@AGhasemzadeh Yes, for now, you can redefine colors in `_variables.scss`. The docs is [here](https://picturepan2.github.io/spectre/getting-started.html#variables-colors).

**Comment by AGhasemzadeh** [comment]
For example colors like: 
http://coreui.io/demo/Ajax_Demo/#main.html
https://adminlte.io/themes/AdminLTE/index2.html

Most customers like dark sidebar like examples.

**Comment by richjdsmith** [comment]
Too much bloat. Just add the through variables.
