### ISSUE TITLE
Improve table and datatable

### ISSUE THREAD

**Issue by AGhasemzadeh** [picturepan2/spectre#360]
Hello,
I like datatable like:  https://modularcode.io/modular-admin-html/items-list.html
Can we have it ?

**Comment by ryan-mahoney** [comment]
What specific aspect(s) are you referring to... the sparklines?

**Comment by AGhasemzadeh** [comment]
No,
Please check it on small device.

**Comment by ryan-mahoney** [comment]
OK, for clarity, the request is that at a certain breakpoint, the table would collapse into two-column view where the left column is the table header fields stacked vertically and the right column contains the table values. This is nice!

**Comment by picturepan2** [comment]
@AGhasemzadeh I think you can do it with JS. I will not include it in Spectre.

**Comment by AGhasemzadeh** [comment]
No, It is not JS.
I think it is diffrent view of responsive table.
We need better table now it is very simple.
