### ISSUE TITLE
block button 100 width 

### ISSUE THREAD

**Issue by AGhasemzadeh** [picturepan2/spectre#365]
hello
i think we need block button 100% width

**Comment by picturepan2** [comment]
@AGhasemzadeh Yes, Spectre has 100% width button [here](https://picturepan2.github.io/spectre/elements.html#buttons-sizes).

**Comment by AGhasemzadeh** [comment]
can we have 100 % only on mobile display?

**Comment by picturepan2** [comment]
@AGhasemzadeh No. No such support yet. May I know when do you need it?
