### ISSUE TITLE
Two end slider ? [enhancement]

### ISSUE THREAD

**Issue by yellowbean** [picturepan2/spectre#372]
Thanks for the great work !!  this css library is always my first choice for all my projects !

I am wondering if it is possible to add a new slider which user can slide both end point to choose a range ? like below ?

![2017-12-28 01_14_24-experimentals - spectre css css framework](https://user-images.githubusercontent.com/1008321/34388141-f281bb70-eb6c-11e7-93da-28b0a2057f85.png)

**Comment by picturepan2** [comment]
@yellowbean I think you will need [this component](https://picturepan2.github.io/spectre/components.html#bars-slider).

**Comment by yellowbean** [comment]
Shame on me , somehow I feel have seen that before.
