### ISSUE TITLE
Responsive form-horizontal

### ISSUE THREAD

**Issue by flec** [picturepan2/spectre#375]
Is there a possibility to have horizontal form responsive, meaning that the form is only horizontal on specific screen sizes (eg. desktop and tablet)? When using `col-xs-12` for both label and field to have the label above the field, the form is still horizontal but both label and field are 100%.
https://jsfiddle.net/179g1nn0/1/

**Comment by Randore** [comment]
.form-horizontal .form-group {
    display: flex;
    display: -ms-flexbox;
    **flex-wrap: wrap;**
}

This will work

**Comment by picturepan2** [comment]
@Randore Thank you. I am adding your suggestion to the Spectre.
