### ISSUE TITLE
Tooltips on anchors persists after click in Chrome

### ISSUE THREAD

**Issue by Doerge** [picturepan2/spectre#377]
Browser: Chrome on OS X.
When tooltips are applied to anchors, they don't disappear after clicking the anchor, but keep hanging around until something else is clicked.

I would expect them to disappear after hoverout, regardless if the anchor has been clicked or not.

Test case:
https://picturepan2.github.io/spectre/components.html#tooltips

It does not happen in Firefox on OS X.

Also thanks for a great project!🙏

**Comment by picturepan2** [comment]
@Doerge Because I added `:focus` to the Tooltips to keep hover text showing. You can remove that line in the `tooltips.scss` source code and re-compile it.

**Comment by Doerge** [comment]
Thanks, that worked perfectly!
