### ISSUE TITLE
any codepen/jsFiddle ?

### ISSUE THREAD

**Issue by JulienJo** [picturepan2/spectre#378]
Hi! 
Nice Framework!

In addition to the documentation, I would like to know if the Spectre components are on codepen or jsFiddle?

Cheers

**Comment by roemhildtg** [comment]
You can easily create a codepen or fiddle by using the cdn:

http://jsbin.com/yavevokire/edit?html,js,output

**Comment by picturepan2** [comment]
@JulienJo @roemhildtg is right. You can use [the CDN files](https://picturepan2.github.io/spectre/getting-started.html#installation).
