### ISSUE TITLE
active/focused state seggestion 

### ISSUE THREAD

**Issue by IgnisFire** [picturepan2/spectre#38]
Can you please think about deleting or replace this behavior  to another class this states of many elements. Many elements such tabs or buttons on click must only do what they need to do, but they after clicking stayed focused. On tabs this behavior reminds active tab and user will be confused. Buttons confusing because  they looks like they lagged or something like that

Sorry for my bad english

**Comment by picturepan2** [comment]
Thank you. I think the problem is that `focus` state looks too similar to `active` state. I will fix it.

**Comment by picturepan2** [comment]
@IgnisFire I updated buttons code. Could you please check if the problem is fixed?

**Comment by IgnisFire** [comment]
Looks fine! But can you also move this functionality to another class? In very few situations need to see focused button or last clicked button. If you don't mind of course

**Comment by picturepan2** [comment]
I think I will keep browser's focus, hover, active behaviors and continue improving visual design to make the states more clear and less confusing. Thank you for the suggestion.

**Comment by IgnisFire** [comment]
Ok. Thank you)

**Comment by victorwpbastos** [comment]
Buttons with class `primary` still have `focused` state after click.

**Comment by picturepan2** [comment]
@victorwpbastos I will fix it in another branch.

**Comment by picturepan2** [comment]
@victorwpbastos @IgnisFire I made a slight change to the focus state of primary buttons just now. I think it is better to have a color change to indicate its different states, especially when people press the tab key to switch among buttons.
