### ISSUE TITLE
Namespace / Prefix by default

### ISSUE THREAD

**Issue by noelboss** [picturepan2/spectre#382]
Please add namespace / prefix for your framework

Using a non-prefixed class like "table" (https://picturepan2.github.io/spectre/elements.html#tables) or "active" can cause problems without namespace. I suggest adding "spectre-table" or "spectre-active" (or whatever prefix you want to use) for everything **by default**, like uikit does it: 
https://getuikit.com/docs/avoiding-conflicts

**Comment by Randore** [comment]
Using namespace is not a compulsory option! if we can manage well in CSS. Though I don't mind using a small namespace - just my 2 cents.

**Comment by picturepan2** [comment]
@noelboss The option is already provided: https://picturepan2.github.io/spectre/getting-started.html#variables-custom-prefix
