### ISSUE TITLE
Enable table scroll on mobile only

### ISSUE THREAD

**Issue by jahirfiquitiva** [picturepan2/spectre#384]
Hello

Thanks for this awesome framework.

I want to add `table-scroll` to a table but it causes it being smaller in desktop, so I was wondering if you could allow it being automatic given the screen width, or if there could be an option to show it with the scroll on mobile only.

Thanks

**Comment by ajusa** [comment]
I am trying to use the table scroll, but it isn't working. When I remove spectre and use just an overflow-x: auto, the table is responsive. What am I doing wrong?

**Comment by picturepan2** [comment]
@jahirfiquitiva There is `table-scroll` class for scrollable tables. https://picturepan2.github.io/spectre/elements.html#tables
