### ISSUE TITLE
World's easiest problem eludes me: missing right margin?

### ISSUE THREAD

**Issue by tomcam** [picturepan2/spectre#385]
Goal is to have a white client area with a gray background. Going slowly insane trying to see what's wrong with this, the world's simplest web page. Left margin is gray as expected, right isn't. Full JSBIN at [http://jsbin.com/gomiyo/edit?html,output](http://jsbin.com/gomiyo/edit?html,output).

```
<head>
	<title>Simple gray background template | Spectre.css</title>
	<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
	<style>
		.container { margin-left: 4rem; margin-right: 4rem; }
		.desktop { background-color: gray; }
		.paper { background-color: white; }
	</style>
</head>
<body>	
	<div class="desktop">
		<div class="container paper">
			<h2>Where's the gray right margin?</h2>
		</div><!-- .container .paper-->
	</div><!-- .desktop -->	
</body>

```

**Comment by tomcam** [comment]
OK, so I it looks like to get the results I want I should add something like .grid-xl along with .container. But I'm still puzzled. The .container class is 100% wide so I don't know why the left margin is visible but the right margin isn't...

**Comment by picturepan2** [comment]
@tomcam Because `.container` is 100% width, it means 100% viewport width. The left margin already uses the viewport space. The right margin is out of the viewport.

**Comment by tomcam** [comment]
Thank you so much!
