### ISSUE TITLE
Does .container serve roughly the same purpose as Bootstrap's container class?

### ISSUE THREAD

**Issue by tomcam** [picturepan2/spectre#386]
A Stackoverflow answer [says succinctly](https://stackoverflow.com/questions/19983857/when-should-i-use-container-and-row-in-twitter-bootstrap-3) that .container is a container of row classes. It seems like it functions similarly in Spectre.css. Is that correct?

Also it appears the the Spectre.css .column class serves roughly the same function as Bootstrap's .row class. Does that sound right?

**Comment by picturepan2** [comment]
@tomcam Yes. Same function.
