### ISSUE TITLE
.container usage outside of columnar layout

### ISSUE THREAD

**Issue by tomcam** [picturepan2/spectre#387]
Does the .container class have any purposes outside of its use in a columnar layout? Or to put it in another way, when is it required  other than when it surrounds .columns divs?

**Comment by picturepan2** [comment]
@tomcam Yes, `.container` class is not only for the column layout. It is also usable for [responsive container](https://picturepan2.github.io/spectre/layout.html#responsive-container).

**Comment by tomcam** [comment]
Thank you so much!
