### ISSUE TITLE
use github-pages / jekyll to build docs

### ISSUE THREAD

**Issue by m5o** [picturepan2/spectre#393]
Your `/docs` directory only contains "compiled" html source code.
Look how projects like Bootstrap, Bulma or Bulmaswatch organize their 
documentation. It's all about small chunks of markdown or example blocks 
which then get automatically build by github.

* https://jekyllrb.com
* https://pages.github.com
* https://github.com/jgthms/bulma/tree/master/docs
* https://github.com/jenil/bulmaswatch/tree/0.6.0

**Comment by picturepan2** [comment]
@m5o Spectre uses Pug to compile the docs now.
