### ISSUE TITLE
Distinguish Badges from Notification Indicators?

### ISSUE THREAD

**Issue by jacksonkernion** [picturepan2/spectre#399]
This isn't super important, but default badge styling doesn't match the default badge styling of [other](https://ionicframework.com/docs/components/#badges) [frameworks](https://getbootstrap.com/docs/4.0/components/badge/). As far as I can tell, badges are usually in line with the text for which they're a badge. (And Spectre, itself, uses inline badges in the menu-item context.) Spectre's default style is more like a notification counter.

I think users expect badges and notification counters to work differently. Notification counters display the number of 'unseen' items, whereas badges display a more persistent count of total items. So it looks to me like clicking on an item with a Spectre-style badge should 'erase' the badge.

So, it would be nice to either:

A. Change the badge styling to be inline.
B. Add a new 'notification indicator' component, and distinguish it from badges.

(Maybe another option is to re-think how chips/badges/labels/counters/indicators are related to one another. Maybe what I'm thinking of as a 'badge' should be treated as 'chip', and what's currently called a badge should be renamed to something else, given how other frameworks use the term 'badge'.)

**Comment by sjclark** [comment]
@jacksonkernion isn't what you're after just the Spectre Chip?
Certainly the Spectre Chip is the analogue of the Bootstrap Badge?

Although I will admit that the Chip element seems to freak out when used in locations where I would've thought it should be fine ala. "And add child text element"

![screen shot 2018-02-12 at 5 23 58 pm](https://user-images.githubusercontent.com/4531017/36083648-973e6c78-1019-11e8-8203-6e9d480e8226.png)

**Comment by jacksonkernion** [comment]
Yeah, I think the the Spectre Chip is probably what I was looking for. Not sure what the best naming conventions are, but the existing vocabulary didn't quite match my mental model.

**Comment by picturepan2** [comment]
@jacksonkernion Please use `label` [link](https://picturepan2.github.io/spectre/elements.html#labels) for inline badge.
