### ISSUE TITLE
Dropdown menu

### ISSUE THREAD

**Issue by shiny** [picturepan2/spectre#40]
Does the menus fit for dropdown?

**Comment by shiny** [comment]
Got the solution.
<code>
<ul>
                        <li>
                            <a><span>选课</span></a>
                            <ul class="menu">
                                <li class="menu-item">
                                    <a href="#menus">
                                        Slack
                                    </a>
                                </li>
                                <li class="menu-item">
                                    <a href="#menus">
                                        Hipchat
                                    </a>
                                </li>
                                <li class="menu-item">
                                    <a href="#menus">
                                    Skype
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
</code>
<code>
    		.top-nav li .menu {
        		position: absolute;
        		display: none;
    		}
    		.top-nav li:hover .menu{
        		display: block;
    		}
</code>

**Comment by picturepan2** [comment]
Yes, you can include the menu component inside a button container. And use `position: absolute;` and `left` and `top` or other CSS code to position it.
