### ISSUE TITLE
No demo for Carousels

### ISSUE THREAD

**Issue by deschant** [picturepan2/spectre#403]
Why is there no demo for the Carousels?

**Comment by cyonder** [comment]
There is: https://picturepan2.github.io/spectre/experimentals.html#carousels

**Comment by deschant** [comment]
I apologize my question was rather ambiguous. I meant to say there is no html markdown demo on how to implement the carousel. I wasn't referring to usage demo.

**Comment by picturepan2** [comment]
@deschant Ah, I see. I will add it. For now, you can view the page source.

**Comment by Vectrex** [comment]
@deschant No. Since the interaction relies on checked states of option-inputs you always have to have user interaction in form of clicks. For automatic playing you will need a small script which toggles the checked properties/attributes of the inputs.
