### ISSUE TITLE
Suggestion: adding name space

### ISSUE THREAD

**Issue by clark-mu** [picturepan2/spectre#405]
Hi

Really appreciate your works. The Spectre is really easy to use and good looking!

Just a tiny suggestion, while I was writing WP plugin with Spectre, there might be some conflicts with the original theme style.css, even in the Admin page. I suppose you can have a namespace for Spectre.

Again, thank you very much for your great work

Clark

**Comment by Vectrex** [comment]
This has already been addressed (and closed) in issue #382

**Comment by picturepan2** [comment]
@clark-mu The solution is already provided: https://picturepan2.github.io/spectre/getting-started.html#variables-custom-prefix
