### ISSUE TITLE
Set the size of inputs/selects in an input group

### ISSUE THREAD

**Issue by oliverjrose99** [picturepan2/spectre#406]
Im using 3 selects in an input group and would like to fix them to all the same size as the width starts out the same but then changes when an option is selected. It changes becuase the select options are made with JS after the HTML is loaded and the inital option for each select is pretty even.
[Image shows the size change](https://i.imgur.com/L6I3Cdx.png)

Is there a way I can fix the size with existing classes or could it be added to the framework?
Thanks

**Comment by Odonno** [comment]
@oliverjrose99 Would it be better to put them in 3 columns? https://picturepan2.github.io/spectre/layout.html#grid

**Comment by picturepan2** [comment]
@oliverjrose99 Try using 
```
.form-select {
  flex: 1 1 0;
}
```
