### ISSUE TITLE
Remove outline of clicked and focused `button` and `a`

### ISSUE THREAD

**Issue by keltik85** [picturepan2/spectre#409]
Whenever I click something I get a **"light-red" box** around that element (mostly `a` and `button`).

Screenshots:
![image](https://user-images.githubusercontent.com/13469004/36791476-4177440a-1c98-11e8-9ecf-20c0e27787f4.png)

I have tried putting this into my scss file, but it does not work:
```
*:visited {outline:none !important}
*:link {outline:none !important}
*:focus {outline:none !important}
*:disabled {outline:none !important}
*:hover {outline:none !important}
*:active {outline:none !important}
button {
	&:visited, &:link,  &:focus, &:disabled, &:hover, &:active {
           outline:none !important
  	}
}
a {
	&:visited, &:link,  &:focus, &:disabled, &:hover, &:active {
            outline:none !important
  	}
}
```

**Comment by Vectrex** [comment]
That's because the border is actually a box-shadow; a `box-shadow: unset` in your custom stylesheet should remove the "border" (I only tried it with Firefox's Developer Tools).

**Comment by keltik85** [comment]
thanks for your quick response, writing it this way did work:
```
button {
        box-shadow: unset
	&:visited, &:link,  &:focus, &:disabled, &:hover, &:active {
                box-shadow: unset;
  	}
}
```
