### ISSUE TITLE
Optionally prefix all class names

### ISSUE THREAD

**Issue by pichfl** [picturepan2/spectre#418]
Spectre is wonderful. I really want to use it for most of my future projects, where it will do a fabulous job maintaining a bit of sanity in my frontend when there is need for basic style and elements.

However using it for existing projects can be very hard, especially since classes can clash with existing code or worse with existing framework behavior which is harder to change. In my case Ember.js adds a `loading` class to all links that are mid transition which can be great, but also can break the layout in unexpected ways because the loading state is not tied to a specific css selector.

This can be fixed rather easily by prefixing all selectors generated by Spectre, which is rather straight forward *and completely optional* when done with Sass. 

I just forked the repository to our company account and will provide a pull request for this until later today. It will default to an empty prefix, meaning no breaking changes for existing users. I'll also add documentation for this where necessary.

**Edit**
As mentioned below, I'm aware of prefixing as a postprocessing step, but this does not work for the Sass source.

**Comment by linuxdoesrock** [comment]
This is already there. 
https://picturepan2.github.io/spectre/getting-started.html#variables-custom-prefix

**Comment by pichfl** [comment]
I forgot to add this reference. This approach does not work for me as I prefer to consume the source files, where this post processing likely fails.

**Comment by picturepan2** [comment]
Thank you. There is already a solution to `Custom prefix` here. https://picturepan2.github.io/spectre/getting-started/custom.html#variables-custom-prefix It is safer and quicker. I fixed the gulp v4 issue in v0.5.9. This will fix your issue.
