### ISSUE TITLE
input has it's own font-size, select does not

### ISSUE THREAD

**Issue by rvmourik** [picturepan2/spectre#42]
Hi There,

Is there a reason why a form-select does not have a font-size and form-input does? This way when you set a font-size in the body {} through CSS, the select font-size changes to the one defined in the body and the input element doesn't.

Thanks.

**Comment by picturepan2** [comment]
@rvmourik I will improve it. Thank you.

**Comment by picturepan2** [comment]
improved in https://github.com/picturepan2/spectre/commit/bde43d1fb817c1ebded1db6c0385cdadccbcd203
