### ISSUE TITLE
Calendar interactive

### ISSUE THREAD

**Issue by mjbates7** [picturepan2/spectre#433]
Hello,

Will the [calendar](https://picturepan2.github.io/spectre/experimentals.html#calendars) ever be interactive (given it's currently experimental) or will it just be for display purposes and we need to add the interactivity to go between months, add events etc ourselves?

Thanks in advance :)

**Comment by Teejay1589** [comment]
**SPECTRE CSS is PURE CSS** which means it will never be interactive.
The Calendar is just for display.
You will have to add you own JS Code to make it interactive.

Too bad I have not tried it out.
So I do not ave a sample code I could provide you to use.

**Comment by mjbates7** [comment]
okay thanks for the quick response.
