### ISSUE TITLE
Accordion documentation incorrect

### ISSUE THREAD

**Issue by brianyuen** [picturepan2/spectre#438]
I could not get the accordion working albeit copying and pasting directly from the documentation. After a bit of head scratching I opened up the browser Dev Tools and inspected how [the example](https://picturepan2.github.io/spectre/components.html#accordions) was working. 

It looks like the working example uses a `for="accordion-1"` while the written out example does not have this. See area wrapped in ** below for what I added to my code to get it working.

```
<!-- standard Accordions example -->
<div class="accordion">
  <input type="checkbox" id="accordion-1" name="accordion-checkbox" hidden>
  <label class="accordion-header" **for="accordion-1"**>
    <i class="icon icon-arrow-right mr-1"></i>
    Title
  </label>
  <div class="accordion-body">
    <!-- Accordions content -->
  </div>
</div>
```

**Comment by picturepan2** [comment]
@brianyuen I will fix it when I release new Pug + Markdown docs update.
