### ISSUE TITLE
How to use with sass

### ISSUE THREAD

**Issue by niahoo** [picturepan2/spectre#439]
Hello, 

Is it possible to use this framework with sass, without filling the DOM with all the classes ?

like this : 

```scss
.my-column {
    @extend .col-md-6;
}
```

Like in here : https://coderwall.com/p/wixovg/bootstrap-without-all-the-debt

Thank you :)

**Comment by Randore** [comment]
Hey, I hope you can write this with any CSS framework which has support for SASS/SCSS.
As you are only **extending** the rules.
--------
I feel SASS improves - speeding development but adds all @parent > child rules for all.

If I am not wrong, even if you do this the compiled version of CSS will add all classes
`eg: #rule .class .somethingelse`

which we can write in css like this
`eg: #rule .somethinglese`

Writing our own CSS styles simplifies codes and even CSS now supports $vars

**Comment by Vectrex** [comment]
Well, since CSS knows nothing about your markup

```CSS
#rule .class .somethingelse
```

is in no way equivalent to

```CSS
#rule .somethingelse
```

One of the reasons why you use Sass and it's nested notation is that you don't have to repeatedly type the nested selectors - not that you can avoid them altogether.

**Comment by Vectrex** [comment]
Having briefly looked over the SCSS files I haven't spotted any type selectors (apart from some in _base.scss). So something like

```CSS
table {
    @extend .table;
}
```

should be perfectly viable.

**Comment by niahoo** [comment]
Hey, I'm sorry, I was misinterpreting Sass docs. What I want is `@include` with mixins. So I have my answer, spectre classes are not declared as mixins.
