### ISSUE TITLE
Column wrapping

### ISSUE THREAD

**Issue by jakobrosenberg** [picturepan2/spectre#44]
Is it possible to have columns that wrap to the next line. This would be useful to show a list of cards.

Examples
http://foundation.zurb.com/sites/docs/grid.html#block-grids
http://v4-alpha.getbootstrap.com/layout/grid/#example-column-wrapping

**Comment by picturepan2** [comment]
@jakobrosenberg I will consider that. Thank you. 😬

**Comment by jakobrosenberg** [comment]
For the moment I'm just adding ``flex-wrap: wrap`` where needed. Works perfectly.

**Comment by picturepan2** [comment]
@jakobrosenberg Yes, you can always custom your own layout with flexbox CSS code.

**Comment by picturepan2** [comment]
I added `col-multiline` to have a multiline grid in https://github.com/picturepan2/spectre/pull/86

**Comment by pmz** [comment]
Exactly what I was looking for!
Would be useful to mention it in the documentation.
Thanks for a great framework @picturepan2 :)
