### ISSUE TITLE
clearfix utilities?

### ISSUE THREAD

**Issue by khalyomede** [picturepan2/spectre#442]
Would be awesome to have clearfixes utilities like:

```html
<div class="clearfix-xs"></div>
<div class="clearfix-sm"></div>
<div class="clearfix-md"></div>
<div class="clearfix-lg"></div>
<div class="clearfix-xl"></div>
```

Keep up the good work!

**Comment by picturepan2** [comment]
@khalyomede Why do you need it?

**Comment by khalyomede** [comment]
Actually there is no issues anymore, after trying [this JSFiddle](http://jsfiddle.net/4g8659uj/14/) every card reset correctly.
