### ISSUE TITLE
could "components - bar" offer different colors?

### ISSUE THREAD

**Issue by igacc** [picturepan2/spectre#446]
i noticed there is a "meters" but the bar with small style is really simple and clear to use, so how can i change the color of it?

the question may be silly, thank you for the great work!

**Comment by Teejay1589** [comment]
.bar .bar-item {
    background: {{ put your color code here e.g #555 }};
}
.bar-slider .bar-slider-btn {
    background: {{ put your color code here e.g #555 }};
}

But

The best way is to change the $primary_color code in _variables.sass and use a SASS Compiler like KOALA to compile it to CSS. 

That way the UI Color is UNIFORM.
