### ISSUE TITLE
Tables should not add thick border bottom to th when inside tbody

### ISSUE THREAD

**Issue by kurthamilton** [picturepan2/spectre#447]
**Feature**
Header row has thick border bottom applied via `.table th` selector.

**Problem**
This does not differentiate between th elements in the thead and the tbody.

**Example**
<table class="table">
<thead>
<tr>
<th></th>
<th>Col 1</th>
<th>Col 2</th>
</tr>
</thead>
<tbody>
<tr>
<th>Row 1</th>
<td>cell</td>
<td>cell</td>
</tr>
<tr>
<th>Row 2</th>
<td>cell</td>
<td>cell</td>
</tr>
</tbody>
</table>

where table has a `table` class applied.

I would want to retain the bold styling for Row 1 and Row 2 th elements, but not have a partial thick border bottom.

**Suggested fix**
Style border bottom with `.table thead th` selector instead of `.table th`.

**Comment by picturepan2** [comment]
@kurthamilton Thanks. Fixing it.

**Comment by picturepan2** [comment]
@kurthamilton It is not a problem. The table cells in `thead` are `th`. Only `th` has thicker bottom border.

**Comment by kurthamilton** [comment]
My point is that you can have 2 types of th:
table > thead > tr > th
table > tbody > tr > th

A thick border bottom is added to both by targeting th. Normal tbody rows have a thin border bottom.

When you have a th in a tbody row, only the th has a thick border bottom. In my opinion this is undesirable and a bug. 

I shall continue to fix with an override of
.table > tbody > tr > th {
  border-bottom-width: $border-width;
}

**Comment by kurthamilton** [comment]
Here's a fiddle to demonstrate:
[https://jsfiddle.net/p1kfsw45/](https://jsfiddle.net/p1kfsw45/)
