### ISSUE TITLE
Problem with input addons width on mobile devices

### ISSUE THREAD

**Issue by sigismund** [picturepan2/spectre#449]
### Feature
Input groups / addons 

### Problem
On mobile devices (<400px) the input overflows out of container/parent element.

### Sample
* https://picturepan2.github.io/spectre/elements.html#forms-input-groups
* [screenshot](https://imgur.com/a/MyxDXnw)

**Comment by picturepan2** [comment]
@sigismund Trying to fix it. Thanks.
