### ISSUE TITLE
tooltip not works when button is disabled

### ISSUE THREAD

**Issue by shiny** [picturepan2/spectre#45]
It's a feature or bug?

If I'd like to display the tooltip on a disabled button, how to do?
Thank you.
`<button class="btn tooltip" data-tooltip="Lorem ipsum dolor sit amet" disabled>top tooltip</button>`

**Comment by picturepan2** [comment]
@shiny I will fix it. Thank you.

**Comment by picturepan2** [comment]
fixed in https://github.com/picturepan2/spectre/commit/15746d90fba75b8845a5f607130ec16ff86f4eb0
