### ISSUE TITLE
`$line-height` is currently undefined in` _variables.scss`

### ISSUE THREAD

**Issue by seanletendre** [picturepan2/spectre#450]
This problem occured when I was trying to rebuild with gulp (the only change I made was to colors).
I just set `$line-height` to `1.5 !default` because that was the value of `$html-line-height`. Should I have set it to something else?

**Comment by picturepan2** [comment]
@seanletendre Hi, here it is:  https://github.com/picturepan2/spectre/blob/master/src/_variables.scss#L73 .
