### ISSUE TITLE
Typo in html code of doc

### ISSUE THREAD

**Issue by ShNURoK42** [picturepan2/spectre#463]
Hi, html code of docs on site has code `<div class="container" id="grid">` (grid) but link on this section in left-side menu is https://picturepan2.github.io/spectre/layout.html#flexbox (flexbox)

**Comment by timogauweiler** [comment]
Same for **Browser support**:

- anchor link: `#browsers`
- anchor name: `#browers`

**Comment by labtocat** [comment]
#469
