### ISSUE TITLE
:lang字体问题

### ISSUE THREAD

**Issue by wolfan** [picturepan2/spectre#467]
把font-family放在:lang()里，设置成了全局，因为无法在使用其它字体，如果在css里重置:lang()又会覆盖掉spectre的列表，比如btn中文字明显上漂变样。

即使在 #div 中设置也无法被使用，只能将spectre的列表重新罗列之后加上自己所需要的字体在列表之后才。

**Comment by picturepan2** [comment]
@wolfan Fixed in v0.5.5. Thanks.
