### ISSUE TITLE
Responsive table?

### ISSUE THREAD

**Issue by iredmail** [picturepan2/spectre#470]
When display a wide table in small screen, it simply shows fist 2-3 columns, no way to check the rest columns. Anyway to make it responsive or even just scrollable?

FYI: tables in responsive design
https://www.liquidlight.co.uk/blog/article/tables-in-responsive-design/

**Comment by ajusa** [comment]
To make a table responsive, add the "table-scroll" class to the table.

**Comment by picturepan2** [comment]
@iredmail @ajusa `table-scroll` is added to the table https://picturepan2.github.io/spectre/elements.html#tables
