### ISSUE TITLE
Wrong font-family set for <code> when set lang attribute to "zh"

### ISSUE THREAD

**Issue by SukkaW** [picturepan2/spectre#476]
I have set `<html lang="zh-CN">` in my project and it override the `font-family` of `<code>` tag to

```css
font-family: -apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"PingFang SC","Hiragino Sans GB","Microsoft YaHei","Helvetica Neue",sans-serif;
```

What should I do? Should I add `lang="en"` attribute to `<code>` tag to solve this?

**Comment by SukkaW** [comment]
Found the same problem at #467

**Comment by picturepan2** [comment]
@SukkaW Your code is in Chinese(zh-CN)?

**Comment by SukkaW** [comment]
@picturepan2 I set `<html lang="zh-Hans">` and cause this issue.
