### ISSUE TITLE
Support for code by markdown-it parser

### ISSUE THREAD

**Issue by codeofsumit** [picturepan2/spectre#481]
Hey there, this is an absolutely great CSS framework. Just switched to it for my latest project and absolutely loving it so far 👍 .

I'm opening this issue as I'm trying to use Spectre with VuePress.
VuePress parses markdown with markdown-it.
The resulting code in a code snipped looks like this:

```HTML
<code>
  <span class="token comment">// yoyo code here</span>
  <span class="token keyword">const</span> a 
  <span class="token operator">=</span> 
  <span class="token number">123</span>
  <span class="token punctuation">;</span>console
  <span class="token punctuation">.</span>
  <span class="token function">log</span>
  <span class="token punctuation">(</span>a
  <span class="token punctuation">)</span>
  <span class="token punctuation">;</span>
</code>
```

while the code blocks on the spectre documentation look like this:
```HTML
<code><span class="hljs-comment">&lt;!-- code snippets --&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">button</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"btn"</span>&gt;</span>
  Submit
<span class="hljs-tag">&lt;/<span class="hljs-name">button</span>&gt;</span>
</code>
```

I'm assuming that Spectre currently supports highlightJS? Markdown-IT seems to be using it too but the output is different. I tried to extend the resulting classes with spectre classes like this:

``` scss
div.language-js pre {
  @extend .code;
}
```

which makes the block better, but the syntax highlighting is missing as I can't import language specifics like these:

``` scss
div.language-js pre {
  @extend .code[data-lang="HTML"];
}
```

Any help is greatly appreciated 👍

**Comment by picturepan2** [comment]
@codeofsumit No, Spectre doesn't provide any code highlight style. It is a complicated project to do. The Spectre Docs pages use few code highlight styles I created only for the docs.
