### ISSUE TITLE
Styling for circle class is missing

### ISSUE THREAD

**Issue by cmarydai** [picturepan2/spectre#489]
Circle class for a round button is missing in the latest update

**Comment by cmarydai** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/0814604a-cc53-47b2-8fdd-a42874e16f0b-728bffb6-9ab0-426a-9f82-71eb44c25550-v1.png?transparent=1&palette=1&width=246)

**Comment by ztiromoritz** [comment]
Seems to be changed from ".circle" to ".s-circle". 
Documentation does not reflect this yet.

**Comment by picturepan2** [comment]
@cmarydai Fixed. Thanks.
