### ISSUE TITLE
Inputs with floating labels

### ISSUE THREAD

**Issue by go4cas** [picturepan2/spectre#49]
It would be cool to have an option for floating labels on text input boxes, similar to material design.

**Comment by victorwpbastos** [comment]
Please, please do that! Would be awesome!

**Comment by picturepan2** [comment]
You mean this label https://www.google.com/design/spec/components/text-fields.html#text-fields-labels?

**Comment by victorwpbastos** [comment]
Yep!

**Comment by herkyl** [comment]
I think it's better to keep Spectre lightweight, if you want a Material Design input then why not use some material design stylesheet, there are tons of them.

**Comment by picturepan2** [comment]
@all I think I will not add that input. That is not Spectre style component. Sorry.
