### ISSUE TITLE
Tooltips on Progress Bars

### ISSUE THREAD

**Issue by optikfluffel** [picturepan2/spectre#493]
It seems Tooltips don't work when used on Progress Bars. Aren't they supposed to do?
I wrote a little example, which I've also put up [at CodePen](https://codepen.io/anon/pen/WgOdrM):

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>Progressbar Tooltip Example</title>

  <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
  <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
</head>

<body>
  <main class="container grid-xs">
    <progress value="25" max="100" data-tooltip="25%" class="progress tooltip tooltip-bottom"></progress>
  </main>
</body>

</html>
```

**Comment by picturepan2** [comment]
![image](https://user-images.githubusercontent.com/126385/45267340-29443080-b49d-11e8-96bd-138b35d44944.png)
It works. What is your browser?

**Comment by picturepan2** [comment]
@optikfluffel It is related to browser's `<progress>` support.

**Comment by optikfluffel** [comment]
@picturepan2 But [according to caniuse.com](https://caniuse.com/#feat=progress) `<progress>` is supported in Safari since version 6, which was released back in July 2012.

**Comment by Tex-tang** [comment]
It seem like it is a bug in Safari, all the elements in the progress tag will be ignored.
