### ISSUE TITLE
How right align elements?

### ISSUE THREAD

**Issue by k0fi** [picturepan2/spectre#495]
Hello,

I'm wondering what is the spectrish way to align elements and text to the right of the page?

**Comment by Teejay1589** [comment]
Use `text-right` class
OR
Force the content with a `float-right` class

**Comment by picturepan2** [comment]
@k0fi Hi, Teejay1589 is right. [text-right](https://picturepan2.github.io/spectre/utilities.html#text) or [float-right](https://picturepan2.github.io/spectre/utilities.html#position).

**Comment by iambudi** [comment]
Is it possible to set the alignment based on column width?
For example on col-sm-12 it should be align right, other than it's align left.
