### ISSUE TITLE
Bar component colors

### ISSUE THREAD

**Issue by tmonte** [picturepan2/spectre#499]
Right now the multi bar example uses inline styles to customize the colors. Shouldn't it use the colors defined in Utilities, more specifically, the bg colors?

Because the default bar item defines a background, I'm unable to use those, since `.bar .bar-item { background: #5755d9 }` is more specific than just `.bg-secondary`.
It would be nice if I could just use the bg colors instead of having to write css for customizing color of the bars.

**Comment by candacej97** [comment]
In the docs the multibar example:

```
<!-- multi-bars -->
<div class="bar">
  <div class="bar-item tooltip" data-tooltip="25%" style="width:25%;">25%</div>
  <div class="bar-item" style="width:15%;background:#818bd5;">15%</div>
</div>
```

the first inner-div doesn't classify a `background-color` and defaults to the default framework's color. You can change the default color in the variables.scss file if you need to.

**Comment by tmonte** [comment]
I don't understand how changing the default color solves the problem.
The issue is that, if you don't set a background via inline styles on the second item, the two bars will have the same exact color (the default one). If I change the default color, they will still have the same color.

What I am trying to do is:
```html
<div class="bar">
  <div class="bar-item bg-success" style="width:25%;">25%</div>
  <div class="bar-item bg-warning" style="width:15%;">15%</div>
  <div class="bar-item bg-error" style="width:10%;">10%</div>
</div>
```
Which does not work, the items are still of the same default color unless I write custom, more specific css to override the default color for each item.

**Comment by candacej97** [comment]
After clarifying, I looked at what you were saying and I see what you mean. The css class declaration `.bar .bar-item` keeps you from implementing the `bg-error` (and others like it) class for the background color.

My advice is to just create classes with the backgrounds you want and add `!important` to your css. Another option would be to use `<span>` tags inside `<div class="bar-item">`, but I would just make my own css declarations.


Best of luck with your project!
