### ISSUE TITLE
ToolTip

### ISSUE THREAD

**Issue by joyguy55** [picturepan2/spectre#500]
Tooltips should really create more of a multiline box. If you only have one or two words appearing they are almost useless. In most cases I've found you need a mini paragraph or at least two lines.

https://docs.cs-cart.com/4.0.x/_images/tooltip1.png

**Comment by loo41** [comment]
For this problem, you can return to the line directly because there is a white-space: pre attribute.

**Comment by picturepan2** [comment]
@joyguy55 Add the `\n` string between any text for line break for multiline tooltips.
