### ISSUE TITLE
table-striped class is missing

### ISSUE THREAD

**Issue by CodeDraken** [picturepan2/spectre#502]
`table-striped` class is missing or it doesn't work.

**Comment by picturepan2** [comment]
@CodeDraken It works and you can see [the demo here](https://picturepan2.github.io/spectre/elements.html#tables).

**Comment by CodeDraken** [comment]
What exactly does it do? @picturepan2 I see no difference and I don't see any styles from `table-striped` in the developer console.

![striped](https://user-images.githubusercontent.com/16908616/45603340-e29c8c00-b9f0-11e8-90fa-e4d368b860ef.png)

![no-stripe](https://user-images.githubusercontent.com/16908616/45603343-e4fee600-b9f0-11e8-8e56-1653e6d08b22.png)

**Comment by CodeDraken** [comment]
> @CodeDraken Don't forget the `<tbody>` tag.

That is from the docs.

**Comment by picturepan2** [comment]
@CodeDraken I don't see the issue here. Do you have online example?

**Comment by CodeDraken** [comment]
The issue is I don't see any stripes. I guess I'm colorblind :thinking: but this is an issue with Bulma CSS itself React components work fine, my mistake.

**Comment by Prid13** [comment]
@CodeDraken just chiming in the from the future to tell you that perhaps you had the **screen brightness** or **contrast** set to too high, making super light grey colors effectively turn into white 😇 -- or maybe you are _indeed_ colorblind, but I really hope it's the former 😅
