### ISSUE TITLE
Popover doesn't work in Mobile Devices

### ISSUE THREAD

**Issue by ekaitz-zarraga** [picturepan2/spectre#503]
I've been unable to activate a popover in a mobile device (iPhone 6s).
Are they supposed to work fine on mobile devices?

**Comment by Tex-tang** [comment]
In my device, yes.
Could you show your code of the popover?

**Comment by ekaitz-zarraga** [comment]
This is my code:

``` html
<div class="popover popover-left text-left">
                <span class="help-text">Ayuda</span>
                <div class="popover-container help-card">
                    <div class="card">
                        <div class="card-body">
                            El gráfico muestra la <em>media</em> en las barras
                            de <span style="color: steelblue">color
                            azul</span>.
                            ...                 
                        </div>
                    </div>
                </div>
            </div>
```

You can see the live version here, in the "Ayuda" button, right under the graph:
https://postdata.biz/es/sociedad_bilbaina/01-ikerYgorka.html

**Comment by ekaitz-zarraga** [comment]
I made it work changing the "span" with a "button" but why in Specre-s page it works with an `a` tag too. I was unable to make it work :face_with_head_bandage:

**Comment by Tex-tang** [comment]
Do this [work](https://stackoverflow.com/questions/35187970/css-hover-not-working-on-ios-safari-and-chrome) for you?

**Comment by ekaitz-zarraga** [comment]
Might be related. With the `button` thing I'm ok but the that point might solve the problem too.
I'll close the issue for the moment and test that anyway.
