### ISSUE TITLE
Can't deactivate component /utilities/_position

### ISSUE THREAD

**Issue by fab4real** [picturepan2/spectre#511]
If you don't import utilities/_position :

> Sass failed to compile with this error: Error: ".container" failed to @extend ".clearfix".
       The selector ".clearfix" was not found.
       Use "@extend .clearfix !optional" if the extend should be able to fail.
        on line 8 of /assets/css/spectre/_layout.scss

**Comment by picturepan2** [comment]
@fab4real I don't think it is good to remove  `utilities/_position`. May I know why you want to remove it?

**Comment by fab4real** [comment]
1- it's an utility and in my opinion should not be required
2- it's absolutely not required to have .float-left or .absolute classes in a project. (but may be required sometime : yes)
3- when importing scss parts, i like to import only files i need and use.
