### ISSUE TITLE
Never use 'transition: all'

### ISSUE THREAD

**Issue by uyouthe** [picturepan2/spectre#526]
So, you've used `transition: all` on a textarea element. It causes textarea resize to lag exactly by duration you've set. I even recorded a [demo](https://youtu.be/v2wAeDmGGW0).

So, it'll be better to remove `transition: all` from the textarea at least, and at most to clean out `transition: all` everywhere along the codebase. It's clearly an antipattern.

**Comment by picturepan2** [comment]
@uyouthe Fixed in v0.5.6. Thank you.
