### ISSUE TITLE
display: none used on input fields makes them innaccessible for screen reader users

### ISSUE THREAD

**Issue by jscholes** [picturepan2/spectre#53]
https://github.com/picturepan2/spectre/blob/master/src/forms.less#L113

    // Form element: Checkbox and radio
    .form-checkbox,
    .form-radio,
    .form-switch {
      input {
        display: none;
      }
    }

Setting display: none on input fields is an accessibility bad practice.  Anybody who uses your framework will automatically be excluding a group of disabled users from using their site effectively.  As framework developers, you need to get this right.

**Comment by picturepan2** [comment]
Firstly, thank you. I admit I didn't consider accessibility completely. Do you know how to make this part better?

**Comment by grahamlicence** [comment]
Hello, I've added a pull request to address this

**Comment by picturepan2** [comment]
@grahamlicence Thank you.

**Comment by picturepan2** [comment]
@jscholes @grahamlicence I fixed it in https://github.com/picturepan2/spectre/pull/73/commits/5a02bda2cc8025e5701acf645ae1d1ec098a515a just like the way @grahamlicence did in your PR. Thank you both.
