### ISSUE TITLE
404 in documentation for button mixins

### ISSUE THREAD

**Issue by lloydjatkinson** [picturepan2/spectre#538]
https://picturepan2.github.io/spectre/elements/getting-started.html#variables-buttons

Results in a 404. I'm not able to find out to create these now.

**Comment by mrmajik45** [comment]
That's... not how it works...

**Comment by devmount** [comment]
The correct link would be:

https://picturepan2.github.io/spectre/getting-started/custom.html#variables-buttons

Where did you find the 404 link @lloydjatkinson ?

**Comment by lloydjatkinson** [comment]
![image](https://user-images.githubusercontent.com/5633938/49040948-cf115c80-f1bb-11e8-8abc-eca6212e66a6.png)


@mrmajik45 Not how what works exactly?
