### ISSUE TITLE
Narrow Column

### ISSUE THREAD

**Issue by dsbert** [picturepan2/spectre#541]
Is it possible to set a column as narrow, only taking as much horizontal space as the content requires?

**Comment by picturepan2** [comment]
@dsbert any example?

**Comment by dsbert** [comment]
I was looking for something similar to https://bulma.io/documentation/columns/sizes/#narrow-column 
 
However, I am going in a different direction and will not be using spectre in the near future (for unrelated reasons).

**Comment by picturepan2** [comment]
@dsbert It is added [here](https://picturepan2.github.io/spectre/layout/grid.html#column-auto). Thanks.
