### ISSUE TITLE
360-Degree Viewer Example in documentation is broken

### ISSUE THREAD

**Issue by christianMurschall** [picturepan2/spectre#546]
Unfortunately the used [background-image](https://i.loli.net/2018/11/25/5bfa45b4b3f27.jpg) link does not load the image due to an invalid certificate. Same applies to the "Photo credits: Microsoft Surface Pro 6" link below the example.

**Comment by picturepan2** [comment]
@christianMurschall What is your network and browser?

**Comment by christianMurschall** [comment]
Company network.... I just checked. From my phone and from home it works.
