### ISSUE TITLE
[solved] modal scroll hidden in mobile size

### ISSUE THREAD

**Issue by ledahu** [picturepan2/spectre#548]
hi

my modal is full of content. 
on large device, scroll are visible, on mobile device, they are hidden 

any solution ?

**Comment by picturepan2** [comment]
@ledahu Screenshots?

**Comment by picturepan2** [comment]
@ledahu I think it is the OS setting to show/auto-hide scrollbar. what is your large device? and mobile device?

**Comment by ledahu** [comment]
yep, solved. FireFow on mobile device don't show scrollbar as expected
