### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by mrioso** [picturepan2/spectre#564]
Card component not show box-shadow property, i found that property is in "node_modules - docs.css", but this styles belongs to spectre's web

**Comment by laodemalfatih** [comment]
yes, the `shadow-box` property is purely a customization of the **spectre** documentation website. If you use pure **spectre**, you won't find that. I'm also confused, why haven't they improved the appearance of their website.

**Comment by picturepan2** [comment]
@mrioso Fixed in v0.5.10 with a new class `card-shadow` will be added.
