### ISSUE TITLE
Loose the advertisement on the docs

### ISSUE THREAD

**Issue by acrodrig** [picturepan2/spectre#569]
The advertisements on the docs are highly distracting. If you want to monetize the project I suggest you double down on Patreon (I just became a one). Or ... at the very least use the less intrusive Carbon base ads.

My two cents.

**Comment by inliquid** [comment]
Yep, and a friendly advice - you'll earn zero from ads for developers, it's nothing but waste of time. I wouldn't even know that they exist, if not discovered few empty blocks on the page while analyzing its layout, and only after seeing class names I paid attention on AdBlock Plus counter, which I actually never look at.

**Comment by picturepan2** [comment]
@acrodrig @inliquid Hi, thanks for the advice and the Patreon help. I'd like to promote Spectre to wider group of developers/designers and it takes money and time. (Honestly, I have a full time job and not always available to improve it or do some more useful tools and libraries. Things will be better when I can monetize it.)
@acrodrig Sorry for those distractions. Please use AdBlock if you want.
