### ISSUE TITLE
icons do not show at all

### ISSUE THREAD

**Issue by yanilkr** [picturepan2/spectre#58]
Tried these in chrome and firefox browsers

`<i class="icon icon-menu"></i> 
<span class="icon icon-favorite_border"></span> `

**Comment by picturepan2** [comment]
@yanilkr Spectre doesn't include these icons. You can use Icomoon.io to make icon font and include font and CSS in your website. Then you can use `<i class="icon icon-menu"></i>` for icons.

For example, Spectre uses [this css](https://picturepan2.github.io/spectre/demo/font/style.css) which generated by Icomoon for icon font.

**Comment by yanilkr** [comment]
makes sense to include icon fonts separate.
