### ISSUE TITLE
Text colors in striped tables

### ISSUE THREAD

**Issue by sebastian0119** [picturepan2/spectre#596]
Hello everybody,
First of all congrats to spectre. I first saw it used on grav CMS and am now trying it out for a project of mine.

Now, my issue is the following:
I am trying to use a striped table on a dark background.
It is striped, but between text color and background color, every second line is completely unreadable. And hovering does not work either. I'm attaching a screen shot for better understanding.

Maybe I am missing some class or something like that, but any help is appreciated.

Thanks in advance,
Sebastian

![striped-table](https://user-images.githubusercontent.com/52871458/61178192-1ca0d500-a5a5-11e9-9cd4-3111b8dabf77.png)

**Comment by tunjioye** [comment]
A quick fix is to make the `.table` class background color white like this
```
.table {
  background: #fff;
}
```
Another Fix is to override spectre.css and customize your own Dark themed table
Check this codepen for more clarity
https://codepen.io/tunjioye/pen/LKoJzR

**Comment by sebastian0119** [comment]
Thanks tunjioye. That worked out great!
