### ISSUE TITLE
Input group fail alignment with Empty state

### ISSUE THREAD

**Issue by mirabalj** [picturepan2/spectre#60]
I tried using a Input group inside a Empty state, but the button loses alignment with the input.

```
<div class="empty">
    <p class="empty-title">You have no new messages</p>
    <p class="empty-meta">Click the button to start a conversation.</p>
    <div class="input-group">
        <span class="input-group-addon">slack.com/</span>
        <input type="text" class="form-input" placeholder="site name" />
        <button class="btn btn-primary input-group-btn">Submit</button>
    </div>
</div>
```
Thanks in advance, good mini-framework!

P.D. View [image](http://imgur.com/YdoS7Hm) for a better idea.

**Comment by Randore** [comment]
Yes, this needs a fix
.empty  .input-group  .btn{ margin:0; }

**Comment by mirabalj** [comment]
Good fix, thanks! @Randore

**Comment by picturepan2** [comment]
@mirabalj I will fix it.

**Comment by picturepan2** [comment]
@mirabalj I fixed it in https://github.com/picturepan2/spectre/pull/73/commits/509206e4714798a6eaddf0065053643a09b5941e. You may need to add `empty-action` to the input group to have a better margin. Here is the doc file:///Users/yanzhu/spectre/index.html#empty.
