### ISSUE TITLE
this project is dead

### ISSUE THREAD

**Issue by publicaccount365** [picturepan2/spectre#616]
this project is dead?

**Comment by rhukster** [comment]
😢

**Comment by laurentpayot** [comment]
@picturepan2 please tell us it is not dead… :pray:

**Comment by picturepan2** [comment]
No, it is alive.

**Comment by Vectrex** [comment]
Good to hear.

**Comment by likelylogic** [comment]
I just had the same question.

Got projects like Tailwind snapping at your heels!

**Comment by EmilStenstrom** [comment]
@picturepan2 Would you be open to accepting new maintainers? They could help you merge pull request and get things going again.

**Comment by Vectrex** [comment]
Same here. If @picturepan2 doesn't accept a new maintainer, I'd go for a fork - any suggestions for a name to avoid confusion?

**Comment by EmilStenstrom** [comment]
@Vectrex No need to jump ahead of ourselves. Yan Zhu has put huge amounts of work into Spectre. It's only fair that she's the one to decide what the next step should be. 

Here's some acknowledgement on Twitter that these issues are seen: https://twitter.com/picturepan2/status/1250030107432898560

**Comment by Vectrex** [comment]
I'd consider forking as a last resort. Having an (additional) maintainer is definitely a better solution. Thanks for the tweet. (And I'm pretty sure "she" is a "he" :-))

**Comment by EmilStenstrom** [comment]
Excellent, then we just have to practice patience :)
