### ISSUE TITLE
Style for type="color"

### ISSUE THREAD

**Issue by dejurin** [picturepan2/spectre#618]

**Comment by dejurin** [comment]
<img width="136" alt="Снимок экрана 2020-01-05 в 20 20 07" src="https://user-images.githubusercontent.com/4470015/71784145-c7e09300-2ff8-11ea-883a-456dfc4df279.png">

**Comment by picturepan2** [comment]
@dejurin You can still use `form-input` class for a color input to change little. There isn't much can do to change the style.
