### ISSUE TITLE
Add an option for gapless grid maybe?

### ISSUE THREAD

**Issue by kevbook** [picturepan2/spectre#62]
See example: 
![unspecified](https://cloud.githubusercontent.com/assets/926720/15544950/9a673de4-2268-11e6-83a6-49ec15f031a7.png)

**Comment by Randore** [comment]
Nice to have, good option but it should be flexible 
eg: I can make one col-6 containing two col-3's to no-gap and leave the other one to full-gap.
Not sure but in some situation we want this.

**Comment by picturepan2** [comment]
@kevbook I will add that. Thank you.

**Comment by picturepan2** [comment]
Yes, I added the option in https://github.com/picturepan2/spectre/pull/73/commits/7f4df64ea3bdf162d2617941aefad2744fd296b2. You can add `col-gapless` to the `columns` elements to have it.
