### ISSUE TITLE
Is Spectre still being maintained?

### ISSUE THREAD

**Issue by webuxr** [picturepan2/spectre#621]
I see the last release was quite a while ago (over a year ago) and we’re still not yet to a stable 1.0.0 release. Is there a roadmap available for future development of the Spectre CSS framework?

**Comment by laurentpayot** [comment]
@webuxr see https://github.com/picturepan2/spectre/issues/616

**Comment by vladrusu** [comment]
To me it looks quite dead, despite author's claims...

**Comment by edelvalle** [comment]
There are 34 pull requests that and a lot of them don't have a single comment from the author.
@picturepan2 if you don't feel like maintaining the project any more, say it and give it away to someone that actually can maintain it.

We love spectre a lot, so don't let it to die...

**Comment by Vectrex** [comment]
This would be the best solution. But why not just "officially" fork it?

**Comment by edelvalle** [comment]
Yes, that's valid... but I will not do it, I don't have the expertise to be the main maintainer I'm not a front-end developer, I use spectre actually because of that, because is 0 JavaScript CSS framework.

**Comment by salamwaddah** [comment]
> Yes, that's valid... but I will not do it, I don't have the expertise to be the main maintainer I'm not a front-end developer, I use spectre actually because of that, because is 0 JavaScript CSS framework.

0 JavaScript makes you lose features like tabs/panels, the current panels is just visuals with the tabs not working because there was plans to add JS.

**Comment by laurentpayot** [comment]
@salamwaddah that's the point of JavaScript-less CSS frameworks: they're not bloated with JS code so you can use React, Vue, Svelte, Elm or whatever is your front-end framework of choice to manage the UI state.

**Comment by Vectrex** [comment]
@salamwaddah - as @laurentpayot said: What JS library or framework (or plain JS) would you use? OTOH Bootstrap has been trying to get rid of its jQuery ties for quite some time now.

**Comment by railsmechanic** [comment]
I have used spectre in some of my projects, just because it is a JavaScript-less CSS framework. I will never understand why so many developers use bloated JavaScript frameworks, with sometimes hundreds of dependencies, just for building web applications which behave exactly like "old school" web applications. Often with the disadvantage that 10MB of JavaScript must be downloaded before one is able to use the "application".

Now in COVID-19 times, our local administration offers the service to apply for financial aid using a web application. When I try to launch this web application with my iPad, I receive a <Hipster Framework> Flow error. Sorry, but such applications must work! Even at the risk of not being fancy.

**Comment by edelvalle** [comment]
I'm totally with @railsmechanic, use JS to introduce some complex behavior, and do it in a conscious way. HTML over the wire still quite good and in a lot of cases faster than bloated SPA.

**Comment by salamwaddah** [comment]
I agree with all of you. but for now we just need @picturepan2 back.

**Comment by bartrylant** [comment]
Yes please, if somebody would take over spectre or if @picturepan2 would come back to maintain it, that would be great. I'm using Spectre for most of my projects lately because it's easy, lightweight and flexible. Don't want to go back to Bootstrap or (even worse) Tailwind…

**Comment by salamwaddah** [comment]
Author [said](https://twitter.com/SalamWaddah/status/1249440867557019648/retweets/with_comments) sure.

![image](https://user-images.githubusercontent.com/26627088/83754824-a8b86100-a67d-11ea-9082-f0bd01be3a5e.png)

**Comment by julienbenisty** [comment]
It's true that it looked very promising and a nice framework. It's already quite stable and usable. But evidently, it has stalled.
Nothing stops anyone from forking it and move on with it. It's licensed under MIT.

**Comment by lu4p** [comment]
It is no longer maintained, I maintain a fork at https://github.com/lu4p/specter, see #633  for details.

**Comment by webuxr** [comment]
Glad to see this project live on here: #633 

https://github.com/lu4p/specter

**Comment by picturepan2** [comment]
@webuxr Sorry, that is a fake project by a liar (The guy changed "credits" after being caught). Please look at #636 real Spectre.css v0.5.9 is updated on July 2, 2020. v0.5.10 and big release is planned as well.

**Comment by dector** [comment]
Thanks a lot for maintaining this. Spectre is very nice and elegant css framework!

**Comment by webuxr** [comment]
> @webuxr Sorry, that is a fake project by a liar (The guy changed "credits" after being caught). Please look at #636 real Spectre.css v0.5.9 is updated on July 2, 2020. v0.5.10 and big release is planned as well.

This is great to hear (not the fake project but that Spectre.css is alive and well). Looking forward to the big release (would this be v0.6 or v1.0?).

Thanks @picturepan2 !
