### ISSUE TITLE
Tooltip on Input not working

### ISSUE THREAD

**Issue by drop1down** [picturepan2/spectre#623]
I was not able to add tooltip to simple Input

`<input class="form-input tooltip" data-tooltip="Lorem ipsum dolor sit amet" type="password" maxLength="50">`

Any idea?

**Comment by kazzkiq** [comment]
Tooltips will not work on self-closing elements such as `<img>` and `<input>`.

You need to add the tooltip to the parent element of your `<input>` e.g.:

```html
<div class="tooltip" data-tooltip="Lorem ipsum dolor sit amet">
  <input class="form-input" type="password" maxLength="50">
</div>
```

**Comment by picturepan2** [comment]
@drop1down @kazzkiq is right. You will need to add `tooltip` to non-selfclosing elements. This is the limitation of pure CSS solution, but still worth using it.
