### ISSUE TITLE
Add icons to form input & textarea, maybe?

### ISSUE THREAD

**Issue by kevbook** [picturepan2/spectre#63]
See example:
1. Icon
   ![unspecified](https://cloud.githubusercontent.com/assets/926720/15545112/26f4815e-2269-11e6-86c6-00f07405b89a.png)
2. Loading icon
   ![unspecified](https://cloud.githubusercontent.com/assets/926720/15545039/e3f3fbaa-2268-11e6-9264-1ed769db1147.png)

**Comment by Randore** [comment]
I think it's already there, what's the point here? http://prntscr.com/b8cml6

**Comment by kevbook** [comment]
Use-case: when you enter the correct slug on the input, and "tick" icon appear.

**Comment by picturepan2** [comment]
@kevbook I will consider that.

**Comment by kevbook** [comment]
If you prefer, I'm happy do a pull request.

**Comment by picturepan2** [comment]
@kevbook Hi, I have added icons for `Forms`. The Form icons section is [here](https://picturepan2.github.io/spectre/elements.html#forms).

**Comment by pspeter3** [comment]
Is it possible to add two form icons to create a numeric stepper?
