### ISSUE TITLE
This Project is no longer maintained, I maintain a Fork

### ISSUE THREAD

**Issue by lu4p** [picturepan2/spectre#633]
The last commit that added functionallity / fixed something was this commit https://github.com/picturepan2/spectre/commit/d30a0a0a00724444b443c6efdeb5594d1c5d499a in December 2018. The author hasn't responded to pull reqests and issues since.

This is why I forked this projected to  https://github.com/lu4p/specter, many of the open pull requests are already merged.

It also has up to date documentation at https://lu4p.github.io/specter/.

Furthermore the ancient tooling of this repo got replaced with something new and shiny.

Feel free to submit pull requests and issues to my fork they will promptly be responded to.

**Comment by Vectrex** [comment]
Good to read.

**Comment by picturepan2** [comment]
You are spamming.
