### ISSUE TITLE
Committing new versions to fight against the spammer and thief

### ISSUE THREAD

**Issue by picturepan2** [picturepan2/spectre#634]
Hello everyone. Thank you for your supports in the past years. I notice @lu4p is copying Spectre without preservation of copyright, change creator info to himself/herself and spam many of you. I am committing new versions right now to fight against the spammer and thief. 

Here is my plan: 

- Update basic things like `devDependencies` and small fixes.
- Review more Pull requests.
- Move forward to a new version.

I still have to do full time work which I am in charge of product, design and dev in a startup.

**Comment by laurentpayot** [comment]
@picturepan2 Welcome back, we missed you! Love this plan.

**Comment by laurentpayot** [comment]
And thanks for the time you invest in this project. IMHO Spectre is better than Bulma (bloated),  what a pity it doesn't get the traction it deserves…

**Comment by gshaw** [comment]
Looks like the fork has been taken down.  Maybe because activity has resumed on this project.
