### ISSUE TITLE
Navbar is not responsive

### ISSUE THREAD

**Issue by jai2010** [picturepan2/spectre#65]
Navbar is not responsive on mobile screen

**Comment by kleninb** [comment]
[http://codepen.io/kleninb/full/YWKOMb](url)
Please check the code and make it better.

**Comment by picturepan2** [comment]
@jai2010 OK. I will try to fix it. Thank you.

**Comment by picturepan2** [comment]
@jai2010 Sorry, I removed Navbar layout. I will add it back when I have a perfect solution.
