### ISSUE TITLE
Add .hide class

### ISSUE THREAD

**Issue by NicoHood** [picturepan2/spectre#654]
I want to use the following code:
```html
for child in collection|slice(0, 4) %}
  <div class="column col-4 col-md-6 col-xs-12 {% if loop.index == 4 %}hide show-md hide-xs{% endif %}">
    {% include 'partials/card.html.twig' with { 'page': child } %}
  </div>
{% endfor %}
```

It should show:
```
default: 3columns, 3 items
xl: 3columns, 3 items
lg: 3columns, 3 items
md: 2columns, 4 items
sm: 2columns, 4 items
xs: 1column, 3 items
```

In order to get this working I needed to add
```css
.hide {
  display: none;
}
```

I think it would make sense to add this tiny feature.

**Comment by adamsir** [comment]
@NicoHood Spectre got you covered by basic set of utility classes. 

Just use `d-none` or `d-hide` https://github.com/picturepan2/spectre/blob/master/src/utilities/_display.scss#L17-L20

Documentation here https://picturepan2.github.io/spectre/utilities/display.html

**Comment by zainsci** [comment]
You can just use style attribute inside the if statement like
```
<div class="column col-4 col-md-6 col-xs-12 {% if loop.index == 4 %}show-md hide-xs{% endif %}" {% if loop.index == 4 %}style="display:none !important"{% endif %}>
```

**Comment by crapthings** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

**Comment by NicoHood** [comment]
I dont know why, but I just noticed the `hide` is not required at all. I dont know how I could oversee this.

@crapthings Also thanks a lot for this useful hint. I guess this issue can be closed then.
