### ISSUE TITLE
Could we remove the background color from empty {}

### ISSUE THREAD

**Issue by kevbook** [picturepan2/spectre#68]
```css
.empty {
  background: #f8f8f8;
}
```

or maybe make it a variable?

**Comment by kleninb** [comment]
<div class="empty empty-default"> </div>

.empty-default {
  background: #f8f8f8;
}

**Comment by picturepan2** [comment]
I make it a variable in https://github.com/picturepan2/spectre/pull/73/commits/6c0bededbae10a3caa8a6cdc10cfee598c6772e8. Thank you.
