### ISSUE TITLE
Tooltips delay?

### ISSUE THREAD

**Issue by Rurik19** [picturepan2/spectre#71]
Is in possible to setup tooltip appearing delay? Say 3sec?

**Comment by picturepan2** [comment]
You could rewrite it with CSS animations. It provides `animation-delay` property to delay tooltip showing up.

**Comment by Rurik19** [comment]
It seems that it doesn't work - tooltip shows immediately

`#card-header {   animation-delay: 3s; }`
` <div class="card-header tooltip" data-tooltip="tooltip" id="card-header">`

**Comment by picturepan2** [comment]
No, sorry, I mean replace `transform` with `animation`.

**Comment by ispal** [comment]
This should work

`.tooltip:hover:after {
      transition-delay: 3s;
    }`
