### ISSUE TITLE
btn-group下的btn-sm边框没有加粗了

### ISSUE THREAD

**Issue by SyanH** [picturepan2/spectre#75]
试了下，貌似是字体太小导致中间的按钮边框没有和边上的按钮边框完美重叠

**Comment by kleninb** [comment]
什么是这里的问题？

**Comment by SyanH** [comment]
@kleninb 更新了浏览器，问题木有了

**Comment by kleninb** [comment]
你可以得到更喜欢哪个浏览器和版本的详细信息。你有没有在其他浏览器如果有可能分享的截图已经检查。
