### ISSUE TITLE
disable hover effect on disabled buttons

### ISSUE THREAD

**Issue by borisirota** [picturepan2/spectre#77]
Currently, when the hover effect in place on disabled buttons, its a little bit confusing and not so intuitive (IMHO) that the button is disabled.

**Comment by initbar** [comment]
Is this in regards to the `background-color` change from white to light blue (hover effect of `Previous` button)?

![screenshot](https://cloud.githubusercontent.com/assets/12630151/15840095/88871fde-2c15-11e6-89e8-5f68e0e6f2d3.png)

**Comment by borisirota** [comment]
Yes. Not applying [this](https://github.com/picturepan2/spectre/blob/master/src/buttons.less#L24), [this](https://github.com/picturepan2/spectre/blob/master/src/buttons.less#L45), [this](https://github.com/picturepan2/spectre/blob/master/src/buttons.less#L72) and [this](https://github.com/picturepan2/spectre/blob/master/src/buttons.less#L116) rules when the button is disabled so you won't see any effect while hovering disabled button.

Exactly like in [bootstrap's disabled button](http://getbootstrap.com/css/#button-element-1) (ignore the cursor).

**Comment by borisirota** [comment]
I'm taking back what I wrote here. Apparently, because the button was with tooltip on it so it what was causing to the live effect. Removing this class when the button is disabled fixed it.
