### ISSUE TITLE
Flexbox grid is broken on small browser window in Safari

### ISSUE THREAD

**Issue by 01010000101001100** [picturepan2/spectre#83]
Here is screenshot with the issue - the layout goes out of the Safari's window:

![screen shot 2016-06-27 at 9 34 05 am](https://cloud.githubusercontent.com/assets/4720153/16366620/8d600b8c-3c4c-11e6-8bee-5bd735b2083b.png)

**Comment by picturepan2** [comment]
What is your Safari version?

**Comment by picturepan2** [comment]
@01010000101001100 Can you show me your code?

**Comment by picturepan2** [comment]
I think it is fixed in latest version https://github.com/picturepan2/spectre/pull/101. You can check it in https://picturepan2.github.io/spectre/. Thank you.
