### ISSUE TITLE
Problem in mobile safari (iOS8 WeChat)

### ISSUE THREAD

**Issue by shiny** [picturepan2/spectre#85]
Modal is hidden, even it has an 'active' className.
Force show it by using jQuery show.It displays, but not have the same style in iOS9.

Does spectre test the compatible in iOS8 mobile safari?

**Comment by picturepan2** [comment]
It should work.

**Comment by shiny** [comment]
@picturepan2 I bought an iPhone(iOS8.4) and finally get the answer:
My build version was missing the `-webkit` prefix.

I have follow the [instruction](http://picturepan2.github.io/spectre/#compiling), with the latest master branch. But the compiled `spectre.css` are not as same as you provided. Still missing  `-webkit` prefix.

Could you give me some advise please?

**Comment by shiny** [comment]
OK I changed the gulpfile.js
from `last 2 versions` to `last 3 versions`
`var autoprefix= new LessPluginAutoPrefix({ browsers: ["last 3 versions"] });`
Now the problem has been solved. 
Is it a bug?

**Comment by picturepan2** [comment]
Partly my mistake. Autoprefixer adds browser vendor prefixes to the CSS. Only Safari on iOS 9 and above supports flexbox layout without `-webkit-`, and Safari on iOS 8.x still needs `-webkit-`. http://caniuse.com/#search=flexbox 

I will change to `last 3 versions` to improve it. Thank you.
