### ISSUE TITLE
Navar is totally destroyed

### ISSUE THREAD

**Issue by ConsoleTVs** [picturepan2/spectre#87]
Hello! in a plain html set the navbar looks totally destroyed:

http://codepen.io/anon/pen/ZOJGPK

**Comment by BlackBooth** [comment]
Navbar was removed 6 days ago (see #86) . If you need it you should use [Release v0.1.23](https://github.com/picturepan2/spectre/releases/tag/v0.1.23)
If you take a quick search on the inserted css on your pen, there is no navbar style

**Comment by Randore** [comment]
@ConsoleTVs 
You can use this code, it works perfectly in all screen sizes.

http://codepen.io/kleninb/pen/YWKOMb

**Comment by picturepan2** [comment]
@ConsoleTVs Sorry, I removed the Navbar code. Because it is too bugy. You can follow @BlackBooth 's method to add it to your own code.
