### ISSUE TITLE
Branches?

### ISSUE THREAD

**Issue by Eun** [picturepan2/spectre#89]
Could you explain which branch is what and where we should checkin out contributions?

I assume master is the latest, but some stuff is missing e.g. navbar.

**Comment by BlackBooth** [comment]
See #87 for navbar support

**Comment by Eun** [comment]
So master is the upstream branch?

**Comment by BlackBooth** [comment]
I guess so. Last PR were merged to master and all open PR want to merge into master too. But in the end only @picturepan2 can answer this.

**Comment by picturepan2** [comment]
@Eun @BlackBooth `master` is the latest and major branch.
