### ISSUE TITLE
Avatar: Initials as fallback

### ISSUE THREAD

**Issue by Eun** [picturepan2/spectre#90]
Use the initals if the picture is not yet loaded or unavailable.
Example code:

    <figure class="avatar" data-initial="YZ" style="background-color: #5764c6;">
        <img src="https://gravatar.com/avatar/d36a92237c75c5337c17b60d90686bf9?size=32"/>
    </figure>

[0002-Initials-as-fallback-avatar.patch.txt](https://github.com/picturepan2/spectre/files/361101/0002-Initials-as-fallback-avatar.patch.txt)

**Comment by nordbit** [comment]
Initaials letters always float over the avatar, no matter of z-index of image avatar

**Comment by picturepan2** [comment]
I have added this in https://github.com/picturepan2/spectre/pull/101. Thank you.
