### ISSUE TITLE
Disabled Button Skin

### ISSUE THREAD

**Issue by Sylencia** [picturepan2/spectre#92]
At the moment, there seems to be no support for a disabled button.
All the button skins currently have a hover/click effect even if disabled, so it's impossible to get a pseudo-disabled skin with what's available.

**Comment by Randore** [comment]
@Sylencia You are right

Solution (using existing disabled class)
`<button class="btn disabled">primary button</button>`

`.btn.disabled{   
  cursor: not-allowed;
  background-color:white;
  opacity:.5;
}`

**Comment by picturepan2** [comment]
@Sylencia Add the class `disabled` or the attribute `disabled` for a disabled button. I am adding the example to the doc.
