### ISSUE TITLE
Tab control within close buttom

### ISSUE THREAD

**Issue by alexsandro-xpt** [picturepan2/spectre#93]
I wish to change tab control to put a close button.

Is this easy?

**Comment by Randore** [comment]
@alexsandro-xpt

https://plnkr.co/edit/c1jmCdwG6afR1qClVDGi?p=preview

**Comment by alexsandro-xpt** [comment]
Really nice @Randore, thank you, now I will put Angular to manage dynamics tabs ;)

**Comment by picturepan2** [comment]
@alexsandro-xpt I have updated the tabs with close button style in v0.2.10 https://github.com/picturepan2/spectre/releases/tag/v0.2.10 .
