### ISSUE TITLE
Tooltip Enhancement

### ISSUE THREAD

**Issue by Randore** [picturepan2/spectre#96]
Instead of adding position classes, I think we can control the tooltip position using CSS only.

**data-pos="left"
data-pos="right"
data-pos="bottom"**

`<button class="btn tooltip" data-tooltip="Lorem ipsum dolor sit amet" data-pos="bottom">top tooltip</button>`

[tooltip.txt](https://github.com/picturepan2/spectre/files/417117/tooltip.txt)

**Comment by picturepan2** [comment]
Thank you. Yes, and I know this. The either way works without problems. The only difference is CSS selector. `[data-pos="xxx"]` is slower than normal classes.
