### ISSUE TITLE
Inconsistent Naming in Responsive Grid

### ISSUE THREAD

**Issue by uyaem** [picturepan2/spectre#97]
First of all, love the framework. Clean and easy to use! :+1: 
But I believe there is a problem, or better an inconsistency with hiding in the responsive grid system.

I was trying to create a layout that has 3 columns + 9 columns on screen width > 600px, and 12 columns when smaller.
The problem is that hide-sm only hides if the screen width is <= 600, but the col-sm-* apply when > 600px.  So if you pair up __hide-sm__ with __col-sm-12__ on two sibling elements, the width range from 481 to 600 is broken as demonstrated in the attached sample.

My suggestion would be to use the variables @size-* as upper bounds for a size.  This would effectively result in
- width <= 480 is xs
- 481 <= width <= 600 is sm
- 601 <= with <= 800 is md
and so on, which is a bit of a paradigm change, but makes sense in my humble opinion, because right now anything <= 480 is not named and thus a bit undefined.

I forked the project and I submitted the changes as pull request #98. :-)

**EDIT:**
Can't seem to upload my example, so I apologize for this badly formatted inline example...
`<div class="container">`
`	<div class="columns" style="height: 100%">`
`		<div class="column hide-sm col-3" style="border: 1px solid black">`
`			Lorem ipsum dolor sit amet...`
`		</div>`
`		<div class="column col-sm-12 col-9" style="border: 1px solid black">`
`			Lorem ipsum dolor sit amet...`
`		</div>`
`	</div>`
`</div>`

**Comment by picturepan2** [comment]
Hi thank you for your suggestion and PR. I have changed the responsive layout in latest version.
