### ISSUE TITLE
Why are there two "col-9" on the Flexbox grid section of index.html?

### ISSUE THREAD

**Issue by carloselhalabi** [picturepan2/spectre#99]
First of all: I love the framework! It is really, really easy to use and has a lot of cool features. With that being said...

When reading the documentation, I couldn't help but notice that on the [Flexbox grid section](https://picturepan2.github.io/spectre/#grid) of the doc are two "col-9" examples. Obviously I think this is wrong and for terms of clarity it should be one. Is this supposed to be like that?

Screenshot:

![screenshot from 2016-09-07 06-41-22](https://cloud.githubusercontent.com/assets/2533088/18313336/4a199e74-74dc-11e6-82b2-50a80ede6e32.png)

**Comment by picturepan2** [comment]
Thank you. I am fixing it in next version.

**Comment by picturepan2** [comment]
Fixed https://github.com/picturepan2/spectre/pull/101
